const unit3_2_sankou = {
    tango: {
        自由研究: { 読み方: ['じゆうけんきゅう'], form: '名詞', 意味: "research project (e.g. at school); independent research" },
        昆虫: { 読み方: ['こんちゅう'], form: '名詞、の形容詞', 意味: "insects" },
        標本: { 読み方: ['ひょうほん'], form: '名詞', 意味: "specimen; sample" },
        昆虫採集: { 読み方: ['こんちゅうさいしゅう'], form: '名詞', 意味: "insect collecting" },
        カブトムシ: { 読み方: [''], form: '名詞', 意味: "rhinoceros beetle" },
        クワガタ: { 読み方: [''], form: '名詞', 意味: "stag beetle" },
        アブラゼミ: { 読み方: [''], form: '名詞', 意味: "brown cicada" },
        ミンミンゼミ: { 読み方: [''], form: '名詞', 意味: "robust cicada" },
        アゲハチョウ: { 読み方: [''], form: '名詞', 意味: "swallowtail butterfly" },
        モンシロチョウ: { 読み方: [''], form: '名詞', 意味: "small cabbage white butterfly" },
        オニヤンマ: { 読み方: [''], form: '名詞', 意味: "jumbo dragonfly" },
        シオカラトンボ: { 読み方: [''], form: '名詞', 意味: "common skimmer" },
        バッタ: { 読み方: [''], form: '名詞', 意味: "locust" },
        カマキリ: { 読み方: [''], form: '名詞', 意味: "praying mantis" },
        キリギリス: { 読み方: [''], form: '名詞', 意味: "grasshopper" },
        生体: { 読み方: ['せいたい'], form: '名詞、の形容詞', 意味: "organism; living body" },
        習性: { 読み方: ['しゅうせい'], form: '名詞', 意味: "habit" },
        昆虫図鑑: { 読み方: ['こんちゅうずかん'], form: '名詞', 意味: "encyclopedia of insects" },
        ひとしきり: { 読み方: [''], form: '副詞、の形容詞', 意味: "for some time; for a while; for a period" },
        画用紙: { 読み方: ['がようし'], form: '名詞', 意味: "drawing paper" },
        宝庫: { 読み方: ['ほうこ'], form: '名詞', 意味: "treasure trove; reservoir" },
        みすぼらしい: { 読み方: [''], form: 'い形容詞', 意味: "shabby" },
        あらためて: { 読み方: [''], form: '副詞', 意味: "once again" },
        始業式: { 読み方: ['しぎょうしき'], form: '名詞', 意味: "opening ceremony (of the school term)" },
        ピンチアウト: { 読み方: [''], form: '', 意味: "pinch out (to zoom in)" },
        お手のもの: { 読み方: ['おてのもの'], form: '名詞', 意味: "one's specialty" },
        声をもらす: { 読み方: ['こえをもらす'], form: '表現、五段動詞、他動詞', 意味: "to let out one's voice" },
        試しに: { 読み方: ['ためしに'], form: '副詞', 意味: "for trial; for testing" },
        ピンチイン: { 読み方: [''], form: '', 意味: "pinch in (to zoom out)" },
        声をあげる: { 読み方: ['こえをあげる'], form: '表現、一段動詞', 意味: "to raise one's voice; to shout" },
        しない手はない: { 読み方: ['〜しないてはない'], form: '表現', 意味: "it would be a waste not to" },
        いずれ劣らぬ: { 読み方: ['いずれおとらぬ'], form: '連体詞', 意味: "equally competent" },
        軍団: { 読み方: ['ぐんだん'], form: '名詞', 意味: "army corps" },
        おやつ: { 読み方: [''], form: '名詞', 意味: "mid-afternoon snack" },
        たいらげる: { 読み方: [''], form: '一段動詞、他動詞', 意味: "to eat up (completely)" },
        ぎょうと: { 読み方: [''], form: '副詞、する動詞', 意味: "to be frightened; startled" },
        上がり込む: { 読み方: ['あがりこむ'], form: '五段動詞、自動詞', 意味: "to enter (house)" },
        とぼとぼと歩く: { 読み方: ['とぼとぼと歩く'], form: '表現、五段動詞', 意味: "to plod; trudge" },
        何気なく: { 読み方: ['なにげなく'], form: '表現、副詞', 意味: "unintentionally; involuntarily" },
        はたと: { 読み方: [''], form: '副詞', 意味: "suddenly" },
        同じく: { 読み方: ['おなじく'], form: '副詞、する動詞', 意味: "same; similarly" },
        指でなぞる: { 読み方: ['ゆびでなぞる'], form: '表現、五段動詞、他動詞', 意味: "to run a finger over~" },
        背後から: { 読み方: ['はいごから'], form: '名詞、の形容詞', 意味: "from behind" },
        ばけもの: { 読み方: [''], form: '名詞', 意味: "monster ghost" },
    },
}

export default unit3_2_sankou;