const unit1_1 = {
    tango: {
        面する: { 読み方: ['（〜に）めんする'], form: 'する動詞', 意味: "to face~" },
        今どき: { 読み方: ['いまどき'], form: '名詞、副詞', 意味: "nowadays" },
        珍しい: { 読み方: ['めずらしい'], form: 'イ形容詞', 意味: "unusual; rare; curious" },
        壁: { 読み方: ['かべ'], form: '名詞', 意味: "wall" },
        立て掛ける: { 読み方: ['（〜に）たてかける'], form: '他動詞', 意味: "ot lean (something against~)" },
        無造作: { 読み方: ['むぞうさ'], form: 'ナ形容詞', 意味: "casual; careless" },
        張り紙: { 読み方: ['はりがみ'], form: '名詞', 意味: "（＝貼り紙）a sign, poster" },
        可能: { 読み方: ['かのう'], form: 'ナ形容詞、名詞', 意味: "possible; potential; feasible" },
        断り書き: { 読み方: ['ことわりガキ'], form: '名詞', 意味: "disclaimer" },
        込める: { 読み方: ['こめる'], form: '一段動詞、他動詞', 意味: "to infuse; load; put" },
        電源コード: { 読み方: ['でんげんコード'], form: '名詞', 意味: "power cord" },
        延びる: { 読み方: ['のびる'], form: '一段動詞、自動詞', 意味: "to extend;" },
        切れる: { 読み方: ['（スイッチが）きれる'], form: '一段動詞、自動詞', 意味: "to be cut; to stop working; to go dead; " },
        ところどころ: { 読み方: [''], form: '副詞、名詞', 意味: "here and there; in places" },
        サビつく: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to rust; to beocme rusty" },
        泥: { 読み方: ['どろ'], form: '名詞', 意味: "mud" },
        泥がはねる: { 読み方: ['どろがはねる'], form: '表現、一段動詞、他動詞', 意味: "to splash with mud" },
        側面: { 読み方: ['そくめん'], form: '名詞', 意味: "side" },
        汚れる: { 読み方: ['よごれる'], form: '一段動詞、自動詞', 意味: "to get dirty; to become dirty" },
        表面: { 読み方: ['ひょうめん'], form: '名詞', 意味: "surface; exterior" },
        プリント: { 読み方: [''], form: '名詞', 意味: "printed images/texts" },
        以前: { 読み方: ['いぜん'], form: '名詞、副詞', 意味: "ago; since; before; previous" },
        恐れがある: { 読み方: ['おそれがある'], form: '表現', 意味: "there is a danger (possibility) that..." },
        明記: { 読み方: ['めいき'], form: '名詞、スル動詞、他動詞', 意味: "clear writing; specification" },
        解釈: { 読み方: ['かいしゃく'], form: '名詞、スル動詞、他動詞', 意味: "interpretation; to interpret (the meaning);" },
        持ち去る: { 読み方: ['もちさる'], form: '五段動詞', 意味: "to take away; to carry away" },
        やつ: { 読み方: [''], form: '名詞、代名詞', 意味: "guy; he/him; [vulgar version of] a \"person\" or a \"thing\"" },
        一度や二度ではない: { 読み方: ['いちどやにどではない'], form: '表現', 意味: "not just once or twice = many times" },
        持ち主: { 読み方: ['もちぬし'], form: '名詞', 意味: "owner" },
        行為: { 読み方: ['こうい'], form: '名詞', 意味: "action; act; deed; conduct" },
        裏側: { 読み方: ['うらがわ'], form: '名詞', 意味: "the reverse side; other side" },
        廊下: { 読み方: ['ろうか'], form: '名詞', 意味: "hallway; corridor" },
        ほっとく: { 読み方: [''], form: '表現', 意味: "＝（人を）ほうっておくto leave someone alone" },
        ある種: { 読み方: ['あるしゅの'], form: '名詞、ノ形容詞', 意味: "a sort of~; certain; some kind of" },
        気に入る: { 読み方: ['きにいる'], form: '表現、五段動詞', 意味: "to like; come into someone's favor" },
        越す: { 読み方: ['こす'], form: '五段動詞、尊敬語', 意味: "to go; to come" },
        瓶: { 読み方: ['びん'], form: '名詞', 意味: "bottle" },
        容器: { 読み方: ['ようき'], form: '名詞', 意味: "container; vessel; packaging" },
        塩: { 読み方: ['しお'], form: '名詞', 意味: "salt" },
        見かける: { 読み方: ['みかける'], form: '一段動詞、他動詞', 意味: "to see; come across; to catch sight of; to (happen to) see" },
        透明: { 読み方: ['とうめい'], form: 'ナ形容詞', 意味: "transparent; clear" },
        蓋: { 読み方: ['ふた'], form: '名詞', 意味: "transparent; clear" },
        穴: { 読み方: ['あな'], form: '名詞', 意味: "hole" },
        振る: { 読み方: ['ふる'], form: '五段動詞、他動詞', 意味: "to wave; to shake" },
        山盛り: { 読み方: ['やまもり'], form: '名詞、ノ形容詞', 意味: "heap" },
        ロビー: { 読み方: [''], form: '名詞', 意味: "lobby" },
        奥: { 読み方: ['おく'], form: '名詞', 意味: "(further in) back" },
        便座: { 読み方: ['べんざ'], form: '名詞', 意味: "toilet seat" },
        目撃: { 読み方: ['もくげき'], form: '名詞、スル動詞、他動詞', 意味: "witnessing; observing; sighting" },
        事実: { 読み方: ['じじつ'], form: '副詞、名詞', 意味: "fact; truth; reality" },
        足跡: { 読み方: ['あしあと'], form: '名詞', 意味: "footprint" },
        後を絶たない: { 読み方: ['あしをたたない'], form: '表現、イ形容詞', 意味: "never ceasing; never ending; endless" },
        事態: { 読み方: ['じたい'], form: '名詞', 意味: "state (of affairs/things); circumstances" },
        特有: { 読み方: ['とくゆう'], form: 'の形容詞、な形容詞', 意味: "characteristic (of); peculiar (of)" },
        比較的: { 読み方: ['ひかくてき'], form: '副詞', 意味: "comparatively; relatively" },
        謎: { 読み方: ['なぞ'], form: '名詞', 意味: "mystery; riddle" },
        板壁: { 読み方: ['いたかべ'], form: '名詞', 意味: "wooden wall" },
        丹念: { 読み方: ['たんねん'], form: 'な形容詞、名詞', 意味: "careful; patient; meticulous" },
        色あせる: { 読み方: ['いろあせる'], form: '一段動詞、自動詞', 意味: "to fade in color" },
        潜む: { 読み方: ['ひそむ'], form: '五段動詞、自動詞', 意味: "to lurk; to be hidden; to be concealed; to be dormant" },
        無法地帯: { 読み方: ['むほうちたい'], form: '名詞', 意味: "lawless area; lawless district" },
        醤油差し: { 読み方: ['しょうゆさし'], form: '名詞', 意味: "soy sauce bottle" },
        爪楊枝: { 読み方: ['つまようじ'], form: '名詞', 意味: "toothpick" },
        ガラス製: { 読み方: ['ガラスせい'], form: 'の形容詞', 意味: "(made of) glass" },
        塞ぐ: { 読み方: ['ふさぐ'], form: '五段動詞、他動詞', 意味: "to block; cover; clog up" },
        金属製: { 読み方: ['きんぞくせい'], form: '名詞、の形容詞', 意味: "(made from) metal; metallic" },
        常人: { 読み方: ['じょうじん'], form: '名詞', 意味: "ordinary person" },


    },

    kaku: {

        こうどう: { 読み方: ['行動'], form: '名詞、スル動詞', 意味: "action; behavior" },
        あいて: { 読み方: ['相手'], form: '名詞', 意味: "partner" },
        かいしゃいん: { 読み方: ['会社員'], form: '名詞', 意味: "company employee; office worker" },
        など: { 読み方: ['～等・（～とう）'], form: '接尾詞、助詞', 意味: "et cetera; the likes of; or something" },
        こじんてき: { 読み方: ['個人的'], form: 'ナ形容詞', 意味: "personal; private; individual" },
        じょうほう: { 読み方: ['情報'], form: '名詞', 意味: "information" },
        しゅっしんち: { 読み方: ['出身地'], form: '名詞', 意味: "birthplace" },
        しゅっしんこう: { 読み方: ['出身校'], form: '名詞', 意味: "alma mater; one's old school or university" },
        せいかく: { 読み方: ['性格'], form: '', 意味: "personality" },
        せわ: { 読み方: ['世話'], form: '名詞、スル動詞', 意味: "care; looking after" },
        ゆうじん: { 読み方: ['友人'], form: '名詞', 意味: "friend" },
        つきあう: { 読み方: ['付き合う'], form: '五段動詞、自動詞', 意味: "to associate with; to keep company with" },
        しょたいめん: { 読み方: ['初対面'], form: '名詞', 意味: "first meeting" },
        じしん: { 読み方: ['自身'], form: '名詞', 意味: "oneself" },
        たにん: { 読み方: ['他人'], form: '名詞', 意味: "another person; other people" },
        べいこくじん: { 読み方: ['米国人'], form: '名詞', 意味: "American person" },
        はずかしい: { 読み方: ['恥ずかしい'], form: 'イ形容詞', 意味: "embarassing" },
        わらう: { 読み方: ['笑う'], form: '五段動詞、自動詞', 意味: "to laugh; to smile" },
        //: { 読み方: [''], form: '', 意味: "" },

    },

    yomerebaii: {

        握手: { 読み方: ['あくしゅ'], form: '名詞、スル動詞', 意味: "handshake" },
        傷つく: { 読み方: ['きずつく'], form: '五段動詞、自動詞', 意味: "to get injured; to get hurt feelings" },
        傷つける: { 読み方: ['きずつける'], form: '一段動詞、他動詞', 意味: "to injure; to hurt someone's feelings" },
        寂しい: { 読み方: ['さびしい'], form: 'イ形容詞', 意味: "lonely" },
        楽天的な: { 読み方: ['らくてんてき'], form: 'ナ形容詞', 意味: "optimistic" },
        社交的: { 読み方: ['しゃこうてき'], form: 'ナ形容詞', 意味: "sociable" },
        素直な: { 読み方: ['すなお'], form: 'ナ形容詞', 意味: "honest; upfront (about one's feelings)" },
        怒る: { 読み方: ['おこる'], form: '五段動詞、自動詞', 意味: "to get angry; to get mad" },
        姿: { 読み方: ['すがた'], form: '名詞', 意味: "figure; form; shape; appearance" },
        積極的な: { 読み方: ['せっきょくてき'], form: 'ナ形容詞', 意味: "proactive; positive" },
        年齢: { 読み方: ['ねんれい'], form: '名詞', 意味: "age" },
        趣味: { 読み方: ['しゅみ'], form: '名詞', 意味: "hobby" },
        打ち明ける: { 読み方: ['うちあける'], form: '一段動詞、他動詞', 意味: "to confide; to disclose; to speak frankly" },
        自己: { 読み方: ['じこ'], form: '名詞', 意味: "self; oneself" },
        開示: { 読み方: ['かいじ'], form: '名詞、スル動詞', 意味: "release (e.g. information)" },
        経験: { 読み方: ['けいけん'], form: '名詞、スル動詞', 意味: "experience" },
        職業: { 読み方: ['しょくぎょう'], form: '名詞', 意味: "occupation" },
        態度: { 読み方: ['たいど'], form: '名詞', 意味: "attitude" },
        恋人: { 読み方: ['こいびと'], form: '名詞', 意味: "lover" },
        問い掛け: { 読み方: ['といかけ'], form: '名詞', 意味: "query; question" },
        即座: { 読み方: ['そくざ'], form: '名詞、副詞', 意味: "right there on the spot; immediately; right away" },
        挙げる: { 読み方: ['あげる'], form: '一段動詞、他動詞', 意味: "to raise; to elevate" },
        異なる: { 読み方: ['ことなる'], form: '五段動詞、自動詞', 意味: "to differ; to vary" },
        //: { 読み方: [''], form: '', 意味: "" },

    },
}

export default unit1_1;