const unit4_1_sankou = {
    tango: {
        婚姻届: { 読み方: ['こんインとどけ'], form: '名詞', 意味: "marriage registration; notification of marriage" },
        欄: { 読み方: ['らん'], form: '名詞、接尾詞', 意味: "field (in a form); section (in a newspaper)" },
        点検: { 読み方: ['てんけん'], form: '名詞、する動詞、多動し', 意味: "to inspect; check; examination" },
        住民票: { 読み方: ['住民票'], form: '名詞', 意味: "certificate of residence" },
        請求: { 読み方: ['せいきゅう'], form: '名詞、する動詞、他動詞', 意味: "to claim; request; demand" },
        押し通す: { 読み方: ['おしとおす'], form: '五段動詞、他動詞', 意味: "to persist in; push through; have one's own way" },
        諭す: { 読み方: ['さとす'], form: '五段動詞、他動詞', 意味: "to admonish; to warn" },
        健康保険証: { 読み方: ['けんこうほけんしょう'], form: '名詞', 意味: "health insurance card" },
        銀行口座: { 読み方: ['ぎんこうこうざ'], form: '名詞', 意味: "bank account" },
        提示: { 読み方: ['ていじ'], form: '名詞、する動詞、他動詞', 意味: "presentation; showing" },
        養子縁組: { 読み方: ['ようしえんぐみ'], form: '名詞', 意味: "adoption (of a person)" },
        煩わしい: { 読み方: ['わずらわしい'], form: 'い形容詞', 意味: "troublesome; annoying" },
        法改正: { 読み方: ['ほうかいせい'], form: '名詞', 意味: "change in law; legal reform" },
        微増: { 読み方: ['びぞう'], form: '名詞、する動詞、自動詞', 意味: "slight increase" },
        就く: { 読み方: ['つく'], form: '五段動詞、自動詞', 意味: "to be employed" },
        葛藤: { 読み方: ['かっとう'], form: '名詞、する動詞、自動詞', 意味: "(feeling of) conflict; reluctance; internal debate" },
        継ぐ: { 読み方: ['つぐ'], form: '五段動詞、他動詞', 意味: "to succeed; inherit; takeover" },
        説得: { 読み方: ['せっとく'], form: '名詞、する動詞、他動詞', 意味: "to persuade" },
        身の上話: { 読み方: ['みのうえばなし'], form: '表現、名詞', 意味: "personal narrative; life story" },
        迫る: { 読み方: ['せまる'], form: '五段動詞、自動詞', 意味: "to press (someone for something); urge" },
        苦痛: { 読み方: ['くつう'], form: 'な形容詞、の形容詞', 意味: "pain; agony" },
        不審がる: { 読み方: ['ふしんがる'], form: '五段動詞', 意味: "to be suspicious (of something or someone)" },
        苦労: { 読み方: ['くろう'], form: '名詞、する動詞', 意味: "to have a hard time" },
        保育園: { 読み方: ['ほいくえん'], form: '名詞', 意味: "nursery school; preschool" },
        付き添う: { 読み方: ['つきそう'], form: '五段動詞、自動詞', 意味: "to escort; to accompany" },
        折々: { 読み方: ['おりおり'], form: '副詞', 意味: "from time to time" },
        しんどい: { 読み方: [''], form: 'い形容詞', 意味: "tiring; tough" },
        陳情: { 読み方: ['ちんじょう'], form: '名詞、する動詞、他動詞', 意味: "to petition; to appeal" },
        事務局長: { 読み方: ['じむきょくちょう'], form: '名詞', 意味: "secretary general" },
        望む: { 読み方: ['のぞむ'], form: '五段動詞、他動詞', 意味: "to hope; want" },
        再婚: { 読み方: ['さいこん'], form: '名詞、する動詞、自動詞', 意味: "to get remarried" },
        戸籍: { 読み方: ['こせき'], form: '名詞', 意味: "family register" },
        戸籍上: { 読み方: ['こせきじょう'], form: '名詞', 意味: "on the family register, offically (legally)" },
        名乗る: { 読み方: ['なのる'], form: '五段動詞、自動詞、他動詞', 意味: "to call oneself" },
        回る: { 読み方: ['まわる'], form: '五段動詞、自動詞', 意味: "to visit several places" },
        採択する: { 読み方: ['採択'], form: '名詞、する動詞、他動詞', 意味: "to adopt (a legislative bill; proposal)" },
        事実婚: { 読み方: ['じじつこん'], form: '名詞', 意味: "common-law marriage; de facto marriage" },
        行政書士: { 読み方: ['ぎょうせいしょし'], form: '名詞', 意味: "certified administrative procedures legal specialist" },
        ペーパー離婚: { 読み方: ['ペーパーりこん'], form: '名詞', 意味: "state of a couple who continue to live together like a married couple even after having legally divorced" },
        取り寄せる: { 読み方: ['とりよせる'], form: '一段動詞、他動詞', 意味: "to order" },
        強制: { 読み方: ['きょうせい'], form: '名詞、する動詞、他動詞', 意味: "enforcement; compulsion" },
        相続: { 読み方: ['そうぞく'], form: '名詞、する動詞、他動詞', 意味: "inheritance; succession" },
        尽きる: { 読み方: ['つきる'], form: '一段動詞、自動詞', 意味: "to be run out; to be used up" },
        ヤジが飛ぶ: { 読み方: ['ヤジがとぶ'], form: '表現', 意味: "[someone] jeers（ヤジを飛ばす：to jeer）" },


    },
}

export default unit4_1_sankou;