const unit2_1 = {
    tango: {
        滞在: { 読み方: ['たいざい'], form: '名詞、する動詞、自動詞', 意味: "stay" },
        駐車場: { 読み方: ['ちゅうしゃじょう'], form: '名詞', 意味: "parking lot; parking garage" },
        白人: { 読み方: ['はくじん'], form: '名詞', 意味: "caucasian" },
        中年男: { 読み方: ['ちゅうねんおとこ'], form: '名詞', 意味: "middle-aged man" },
        呼び止める: { 読み方: ['よびとめる'], form: '一段動詞、他動詞', 意味: "to (call to) stop [someone]" },
        日焼けする: { 読み方: ['ひやけする'], form: '名詞、する動詞、自動詞', 意味: "sunburn; suntan; become discolored from the sun" },
        簡素: { 読み方: ['かんそ'], form: 'な形容詞、名詞', 意味: "modest; simple; plain" },
        衣服: { 読み方: ['いふく'], form: '名詞', 意味: "clothes" },
        服装: { 読み方: ['ふくそう'], form: '名詞', 意味: "garments; attire" },
        市民: { 読み方: ['しみん'], form: '名詞', 意味: "citizen; city inhabitant; townspeople" },
        見分けがつかない: { 読み方: ['みわけがつかない'], form: '表現', 意味: "indistinguishable" },
        見分け: { 読み方: ['みわけ'], form: '名詞', 意味: "distinction" },
        見分ける: { 読み方: ['みわける'], form: '一段動詞、他動詞', 意味: "to distinguish; to recognize; to tell apart; to differentiate" },
        おおよそ: { 読み方: [''], form: '副詞', 意味: "about; roughly; approximately; generally" },
        想像がつく: { 読み方: ['そうぞうがつく'], form: '表現、五段動詞', 意味: "ot be imaginable; to be conceivable" },
        お腹が減る: { 読み方: ['おなかがへる'], form: '表現、五段動詞', 意味: "to become hungry" },
        小銭: { 読み方: ['こぜに'], form: '名詞', 意味: "small change; coins" },
        呼びかける: { 読み方: ['よびかける'], form: '一段動詞、他動詞', 意味: "to address; call (for help)" },
        金額: { 読み方: ['きんがく'], form: '名詞', 意味: "amount of money; sum of money" },
        限定: { 読み方: ['げんてい'], form: '名詞、する動詞、他動詞', 意味: "limit; restriction" },
        援助: { 読み方: ['えんじょ'], form: '名詞、する動詞、他動詞', 意味: "assistance; aid; support" },
        求める: { 読み方: ['もとめる'], form: '一段動詞、他動詞', 意味: "to want; to wish for; to request" },
        焼く: { 読み方: ['やく'], form: '五段動詞、他動詞', 意味: "to burn; to grill; to heat; to heat up" },
        匂い: { 読み方: ['におい'], form: '名詞', 意味: "odor; scent; aura" },
        漂う: { 読み方: ['ただよう'], form: '五段動詞、自動詞', 意味: "to drift; to float; to waft (e.g. a scent)" },
        つらい: { 読み方: [''], form: 'い形容詞', 意味: "painful; bitter; heart-breaking; difficult (emotinally)" },
        同情: { 読み方: ['どうじょう'], form: '名詞、する動詞、自動詞', 意味: "sympathy; compassion; pity" },
        確か: { 読み方: ['たしか'], form: 'な形容詞、名詞', 意味: "sure; certain; positive; definite; reliable; trustworthy" },
        全く: { 読み方: ['まったく'], form: '副詞、の形容詞', 意味: "really; truly; entirely; completely; good grief" },
        訴える: { 読み方: ['うったえる'], form: '一段動詞、他動詞', 意味: "to bring to (someone's attention); to appeal to (reason, emotions, etc.); to play on (one's sympathies); to sue" },
        企画力: { 読み方: ['きかくりょく'], form: '名詞', 意味: "planning ability" },
        素直: { 読み方: ['すなお'], form: 'な形容詞', 意味: "honest; frank; upfront (about one's feelings)" },
        感心: { 読み方: ['かんしん'], form: '名詞、する動詞', 意味: "admiration; being impressed" },
        にこりともせずに: { 読み方: [''], form: '表現', 意味: "with no smile" },
        突っ込む: { 読み方: ['つっこむ'], form: '五段動詞、他動詞', 意味: "to thrust (something) into (something); to cram; to stuff; to shove" },
        音を立てる: { 読み方: ['おとをたてる'], form: '表現、一段動詞', 意味: "to make a sound" },
        浮かぶ: { 読み方: ['うかぶ'], form: '五段動詞', 意味: "to float; to be suspended" },
        考えが浮かぶ: { 読み方: ['かんがえがうかぶ'], form: '表現', 意味: "to have an idea; idea occurs to [person]" },
        手遅れ: { 読み方: ['ておくれ（だ／になる）'], form: '名詞', 意味: "being too late; losing one's final chance" },
        街角: { 読み方: ['まちかど'], form: '名詞', 意味: "street corner" },
        微か: { 読み方: ['かすか'], form: 'な形容詞', 意味: "slight; faint; subtle" },
    },

    kaku: {
        ちゅうしゃじょう: { 読み方: ['駐車場'], form: '名詞', 意味: "parking lot" },
        ちゅうねん: { 読み方: ['中年'], form: '名詞、の形容詞', 意味: "middle-age" },
        ひやけ: { 読み方: ['日焼け'], form: '名詞、する動詞、自動詞', 意味: "sunburn; suntan" },
        かんそ: { 読み方: ['簡素'], form: 'な形容詞、名詞', 意味: "modest; simple; plain" },
        いふく: { 読み方: ['衣服'], form: '名詞', 意味: "clothes" },
        かんする: { 読み方: ['（〜に）関する'], form: 'するどうし', 意味: "to concern; to be related" },
        しみん: { 読み方: ['市民'], form: '名詞', 意味: "citizen; townsfolk" },
        みわけ: { 読み方: ['見分け'], form: '名詞', 意味: "distinction" },
        きんがく: { 読み方: ['金額'], form: '名詞', 意味: "amount of money; sum of money" },
        げんてい: { 読み方: ['限定'], form: '名詞、する動詞、の形容詞', 意味: "limit; restriction" },
        もとめる: { 読み方: ['求める'], form: '一段動詞、他動詞', 意味: "to want; to wish for; to request" },
        やく: { 読み方: ['焼く'], form: '五段動詞、他動詞', 意味: "to burn; to heat; to grill" }, 
        におい: { 読み方: ['匂い'], form: '名詞', 意味: "scent; aroma" },
        どうじょう: { 読み方: ['同情'], form: '名詞、する動詞、自動詞', 意味: "sympathy; compassion; pity" },
        さつ: { 読み方: ['札'], form: '名詞', 意味: "banknote; bill; paper money" },
        ておくれ: { 読み方: ['手遅れ'], form: '名詞', 意味: "being too late; losing one's final chance" },
    },

    yomerebaii: {
        滞在: { 読み方: ['たいざい'], form: '名詞、する動詞、自動詞', 意味: "stay" },
        髪: { 読み方: ['かみ'], form: '名詞', 意味: "hair (on the head)" },
        服装: { 読み方: ['ふくそう'], form: '名詞', 意味: "attire; garment" },
        お腹: { 読み方: ['おなか'], form: '名詞', 意味: "belly; stomach" },
        街角: { 読み方: ['まちかど'], form: '名詞', 意味: "street corner" },
        小銭: { 読み方: ['こぜに'], form: '名詞', 意味: "small change; coins" },
        援助: { 読み方: ['えんじょ'], form: '名詞、する動詞、他動詞', 意味: "assistance; aid; support" },
        漂う: { 読み方: ['ただよう'], form: '五段動詞、自動詞', 意味: "to drift; to float; to waft (e.g. a scent)" },
        訴える: { 読み方: ['うったえる'], form: '一段動詞、他動詞', 意味: "to bring to (someone's attention); to appeal to (reason, emotions, etc.); to play on (one's sympathies); to sue" },
        企画力: { 読み方: ['きかくりょく'], form: '名詞', 意味: "planning ability" },
        財布: { 読み方: ['さいふ'], form: '名詞', 意味: "wallet; handbag; purse" },
        浮かぶ: { 読み方: ['うかぶ'], form: '五段動詞', 意味: "to float; to be suspended" },
    },
}

export default unit2_1;