const unit2_2 = {
    tango: {
        教訓: { 読み方: ['きょうくん'], form: '名詞、する動詞、他動詞', 意味: "lesson, teachings, moral" },
        ある程度: { 読み方: ['あるていど'], form: '表現、の形容詞、副詞', 意味: "to some extent; to a certain extent" },
        領域: { 読み方: ['りょういき'], form: '名詞、の形容詞', 意味: "area; domain; region" },
        単に: { 読み方: ['たんに'], form: '副詞', 意味: "simply; merely; only" },
        義務的: { 読み方: ['ぎむてき'], form: 'な形容詞', 意味: "obligatory; mandatory" },
        具体的: { 読み方: ['ぐたいてき'], form: 'な形容詞', 意味: "specific; substantial; concrete; definite" },
        率直: { 読み方: ['そっちょく'], form: 'な形容詞、名詞', 意味: "straightforward; frank; direct; candid" },
        提出: { 読み方: ['ていしゅつ'], form: '名詞、する動詞、他動詞', 意味: "turning in; submission (of an application, report, etc.)" },
        他人事: { 読み方: ['たにんごと'], form: '名詞', 意味: "someone else's problem; other people's affairs" },
        事情: { 読み方: ['じじょう'], form: '名詞', 意味: "state of affairs; circumstances; conditions; situation" },
        反射的: { 読み方: ['はんしゃてき'], form: 'な形容詞', 意味: "reflexive; reflecting" },
        わずか: { 読み方: [''], form: 'な形容詞', 意味: "a little; a few; slight; small amount; only; just; merely" },
        隅: { 読み方: ['すみ'], form: '名詞、接尾詞', 意味: "corner; nook" },
        接す: { 読み方: ['せっす［＝coll.接する］'], form: 'する動詞、自動し、他動詞', 意味: "to treat someone; to come in contact with; to take care of; to look after; to connect" },
        接し方: { 読み方: ['（〜との）せっしかた'], form: '名詞', 意味: "the way someone treats (people)" },
        蝶: { 読み方: ['ちょう'], form: '名詞', 意味: "butterfly" },
        担任教師: { 読み方: ['たんにんきょうし'], form: '名詞', 意味: "class teacher" },
        胸: { 読み方: ['むね'], form: '名詞', 意味: "chest; heart; mind; feelings" },
        突き刺さる: { 読み方: ['つきささる'], form: '五段動詞、自動詞', 意味: "to stick into; to pierce" },
        チクリと: { 読み方: [''], form: '副詞', 意味: "prickling; stinging; biting" },
        痛む: { 読み方: ['いたむ'], form: '五段動詞、自動詞', 意味: "to hurt; to ache; to feel a pain" },
        当時: { 読み方: ['とうじ'], form: '名詞、副詞', 意味: "at that time; in those days" },
        いじめる: { 読み方: [''], form: '一段動詞、他動詞', 意味: "to ill-treat; to bully; to torment; to pick on; to tease" },
        避ける: { 読み方: ['さける'], form: '一段動詞、他動詞', 意味: "to avoid (physical contact with); to avoid (situation)" },
        いじめ: { 読み方: [''], form: '名詞', 意味: "bullying; teasing" },
        手を焼く: { 読み方: ['てをやく'], form: '表現、五段動詞', 意味: "do not know what to do with; to be at a loss with; to have difficulty with" },
        うなずき返す: { 読み方: ['うなずきかえす'], form: '五段動詞、自動詞', 意味: "to nod back" },
        今更: { 読み方: ['いまさら'], form: '副詞', 意味: "now (after such a long time); it's too late (to~)" },
        生意気: { 読み方: ['なまいき'], form: 'な形容詞、名詞', 意味: "impertinent; cheeky; impudent; audacious; cocky" },
        クモの巣: { 読み方: ['クモのす'], form: '名詞', 意味: "spider's web" },
        引っ掛かる: { 読み方: ['ひっかかる'], form: '五段動詞、自動詞', 意味: "to get stuck; to get caught" },
        はらう: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to brush off; to slap away" },
        にこにこ: { 読み方: [''], form: '副詞、する動詞', 意味: "smilingly; with a friendly grin" },
        出来事: { 読み方: ['できごと'], form: '名詞', 意味: "incident; affair; happening; event" },
        日記: { 読み方: ['にっき'], form: '名詞', 意味: "diary; journal" },
        花丸: { 読み方: ['はなまる'], form: '名詞', 意味: "encircled flower seal" },
        返却: { 読み方: ['へんきゃく'], form: '名詞、する動詞、他動詞', 意味: "return of something; repayment" },
        息が詰まる: { 読み方: ['いきがつまる'], form: '表現、五段動詞', 意味: "to feel suffocate; to choke; to have trouble breathing" },
        思いやる: { 読み方: ['おもいやる'], form: '五段動詞、他動詞', 意味: "to be considerate; to sympathise with ［n.思いやり］" },
        理論的: { 読み方: ['りろんてき'], form: 'な形容詞', 意味: "theoretical" },
        響く: { 読み方: ['ひびく'], form: '五段動詞、自動詞', 意味: "to resound; to have an effect; to make an impression" },
        基本: { 読み方: ['きほん'], form: '名詞、の形容詞', 意味: "basics; basis; foundation; fundamentals" },
    },

    kaku: {
        ていど: { 読み方: ['程度'], form: '名詞、副詞、接尾詞', 意味: "degree; amount" },
        たんに: { 読み方: ['単に'], form: '副詞', 意味: "simply; merely" },
        ぐたいてき: { 読み方: ['具体的'], form: 'な形容詞', 意味: "specific; definite; concrete" },
        じじょう: { 読み方: ['事情'], form: '名詞', 意味: "circumstances; conditions; situation; state of affairs" },
        はんしゃてき: { 読み方: ['反射的'], form: 'な形容詞', 意味: "reflexive; reflecting" },
        こうふく: { 読み方: ['幸福'], form: '名詞、な形容詞', 意味: "happiness; well-being; joy" },
        いのる: { 読み方: ['祈る'], form: '五段動詞、他動詞', 意味: "to pray; to wish" },
        せっす: { 読み方: ['接する／接す'], form: '五段動詞、する動詞、自動詞', 意味: "to treat; to come in contact with" },
        やさしい: { 読み方: ['優しい'], form: 'い形容詞', 意味: "tender; kind; gentle; affectionate; amiable" },
        きょうし: { 読み方: ['教師'], form: '名詞', 意味: "先生" },
        つきささる: { 読み方: ['突き刺さる'], form: '五段動詞、自動詞', 意味: "to stick into; to pierce" },
        いたむ: { 読み方: ['痛む'], form: '五段動詞、自動詞', 意味: "to hurt; to ache; to feel a pain" },
        とうじ: { 読み方: ['当時'], form: '名詞、副詞', 意味: "at that time; in those days" },
        なまいき: { 読み方: ['生意気'], form: 'な形容詞', 意味: "impertinent; audacious; cocky; cheeky" },
        できごと: { 読み方: ['出来事'], form: '名詞', 意味: "incident; affair; happening; event" },
        にっき: { 読み方: ['日記'], form: '名詞', 意味: "diary; journal" },
        はなまる: { 読み方: ['花丸'], form: '名詞', 意味: "encircled flower seal" },
        いき: { 読み方: ['息'], form: '名詞', 意味: "breath; breathing" },
        つまる: { 読み方: ['詰まる'], form: '五段動詞、自動詞', 意味: "to be packed (with); to be blocked; to be clogged" },
        りろんてき: { 読み方: ['理論的'], form: 'な形容詞', 意味: "theoretical" },
        いらい: { 読み方: ['以来'], form: '名詞、副詞', 意味: "since; henceforth" },
        つねに: { 読み方: ['常に'], form: '副詞', 意味: "always; constantly" },
        きほん: { 読み方: ['基本'], form: '名詞、の形容詞', 意味: "basics; fundamentals; basis; foundation" },
    },

    yomerebaii: {
        教訓: { 読み方: ['きょうくん'], form: '名詞', 意味: "moral; lesson; teachings" },
        隅: { 読み方: ['すみ'], form: '名詞', 意味: "corner; nook" },
        胸: { 読み方: ['むね'], form: '名詞', 意味: "chest" },
        巣: { 読み方: ['す'], form: '名詞', 意味: "nest; breeding place; hive; (spider's) web; den" },
        提出: { 読み方: ['ていしゅつ'], form: '名詞、する動詞、他動詞', 意味: "turning in; submission (of an application, report, etc.)" },
        一連: { 読み方: ['いちれん'], form: '名詞、の形容詞', 意味: "series" },
        意気揚々: { 読み方: ['いきようよう'], form: 'たる形容詞、と副詞', 意味: "triumphant; in high and proud spirits" },
    },
}

export default unit2_2;