const unit3_2 = {
    tango: {
        悔しい: { 読み方: ['くやしい'], form: 'い形容詞', 意味: "frustrated (over a failure, humiliation, or injustice); annoyed; dissapointed; bitter" },
        自慢: { 読み方: ['じまん'], form: '名詞、する動詞、の形容詞、他動詞', 意味: "pride; boast" },
        自信: { 読み方: ['じしん'], form: '名詞、する動詞', 意味: "self-confidence" },
        捕る: { 読み方: ['とる'], form: '五段動詞、他動詞', 意味: "to take; to catch; to capture" },
        実物: { 読み方: ['じつぶつ'], form: '名詞、の形容詞', 意味: "real thing; original; actual" },
        満足: { 読み方: ['まんぞく'], form: '名詞、な形容詞、する動詞', 意味: "satisfaction; sufficient; satisfactory; enough; contentment" },
        ついさっき: { 読み方: [''], form: '表現、の形容詞、副詞', 意味: "just now; a little while back; a short time ago" },
        同級生: { 読み方: ['どうきゅうせい'], form: '名詞', 意味: "classmate" },
        発売: { 読み方: ['はつばい'], form: '名詞、する動詞、他動詞', 意味: "sale; offering for sale; release (for sale); launch (product)" },
        流れ: { 読み方: ['ながれ'], form: '名詞', 意味: "lfow (of a fluid or gas or of people, things); stream; current; course (of events)" },
        本格的: { 読み方: ['ほんかくてき'], form: 'な形容詞', 意味: "genuine; real; authentic; orthodox; full-fledged" },
        現地: { 読み方: ['げんち'], form: '名詞', 意味: "actual place; actual location; the spot; the scene; place where one is currently living" },
        頷く: { 読み方: ['うなずく'], form: '五段動詞、自動詞', 意味: "to nod; to bow one's head in assent" },
        みじめ: { 読み方: [''], form: 'な形容詞', 意味: "miserable; wretched; unhappy; sad" },
        悪気: { 読み方: ['わるぎ'], form: '名詞', 意味: "ill will; malice; evil intent" },
        文句: { 読み方: ['もんく'], form: '名詞', 意味: "complaint; grumbling; objection" },
        情けない: { 読み方: ['なさけない'], form: 'い形容詞', 意味: "miserable; shameful; pathetic" },
        立派: { 読み方: ['りっぱ'], form: 'な形容詞', 意味: "splendid; fine; praiseworthy" },
        ただ: { 読み方: ['ただの［名詞］'], form: 'の形容詞', 意味: "just~; ordinary; common; usual" },
        価値: { 読み方: ['かち'], form: '名詞', 意味: "value; worth; merit" },
        親指: { 読み方: ['おやゆび'], form: '名詞', 意味: "thumb; big toe" },
        人差し指: { 読み方: ['ひとさしゆび'], form: '名詞', 意味: "index finger" },
        間隔: { 読み方: ['かんかく'], form: '名詞', 意味: "space; interval; space character; whitespace" },
        画面: { 読み方: ['がめん'], form: '名詞', 意味: "screen (of a TV, computer, etc.)" },
        拡大: { 読み方: ['かくだい'], form: '名詞、する動詞、他動詞、自動詞', 意味: "magnification; enlargement; expansion; extension" },
        操作: { 読み方: ['そうさ'], form: '名詞、する動詞、他動詞', 意味: "operation; management; handling" },
        冗談: { 読み方: ['じょうだん'], form: '名詞', 意味: "joke;jest; funny story" },
        思わず: { 読み方: ['おもわず〜'], form: '副詞', 意味: "unconsciously; instinctively" },
        つまむ: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to pinch" },
        動作: { 読み方: ['どうさ'], form: '名詞、する動詞', 意味: "movement (of the body); action; motion; operation (of a machine, software, etc.)" },
        もと: { 読み方: ['もとの'], form: 'の形容詞', 意味: "former~; original~" },
        確認: { 読み方: ['かくにん'], form: '名詞、する動詞、他動詞', 意味: "confirmation; verification; validation" },
        利用: { 読み方: ['りよう'], form: '名詞、する動詞、他動詞', 意味: "use; utilization; application" },
        次から次へと: { 読み方: [''], form: '表現', 意味: "one after another" },
        作業: { 読み方: ['さぎょう'], form: '名詞、する動詞', 意味: "work; operation" },
        巨大: { 読み方: ['きょだい'], form: 'な形容詞、名詞', 意味: "huge; gigantic; enormous" },
        級: { 読み方: ['〜きゅう'], form: '名詞、接尾辞', 意味: "class; grade; rank" },
        しばらく: { 読み方: [''], form: '副詞、する動詞', 意味: "for a moment; for a minute; for a while; for some time; for the time being; for now" },
        にんまりと: { 読み方: [''], form: '副詞、と副詞、する動詞', 意味: "with a complacent smile; with a smile of satisfaction" },
        取り出す: { 読み方: ['とりだす'], form: '五段動詞、他動詞', 意味: "to take out; to produce; to fetch; to retrieve" },
        拭く: { 読み方: ['ふく'], form: '五段動詞、他動詞', 意味: "to wipe; to dry" },
        ばったり: { 読み方: ['ばったり会う'], form: '副詞、と副詞', 意味: "unexpectedly (meeting someone); to bump into~" },
        警察: { 読み方: ['けいさつ'], form: '名詞', 意味: "police" },
        真剣: { 読み方: ['しんけん'], form: 'な形容詞', 意味: "serious; earnest" },
        必死: { 読み方: ['ひっし'], form: 'な形容詞、の形容詞', 意味: "frantic; desparate" },
        無駄: { 読み方: ['むだ'], form: 'な形容詞、名詞', 意味: "futility; waste; uselessness; pointlessness" },
        駆ける: { 読み方: ['かける'], form: '一段動詞、自動詞', 意味: "to run; to dash; to race" },
        飛び出す: { 読み方: ['とびだす'], form: '五段動詞、自動詞', 意味: "to jump out; to rush out; to fly out; to appear (suddenly)" },
        商店街: { 読み方: ['しょうてんがい'], form: '名詞', 意味: "shopping district; shopping street; downtown" },
        立ち止まる: { 読み方: ['たちどまる'], form: '五段動詞、自動詞', 意味: "to stop (in one's tracks); to come to a stop; to halt" },
        映る: { 読み方: ['うつる'], form: '五段動詞、自動詞', 意味: "to be reflected; to be projected; to be displayed (on a screen)" },
        こする: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to rub; to scrub; to scrape" },
        再度: { 読み方: ['さいど'], form: '副詞、名詞', 意味: "a second time; again; once more; twice" },
        まくる: { 読み方: ['V[STEM]ーまくる'], form: '五段動詞、補助動詞', 意味: "to V over and over again" },
    },

    kaku: {
        じしん: { 読み方: ['自信'], form: '名詞、する動詞', 意味: "self-confidence; confidence (in oneself)" },
        じつぶつ: { 読み方: ['実物'], form: '名詞', 意味: "real thing; original" },
        はつばい: { 読み方: ['発売'], form: '名詞、する動詞、他動詞', 意味: "sale; offering for sale; release (for sale)" },
        ながれ: { 読み方: ['流れ'], form: '名詞', 意味: "flow (of a fluid, gas, people, things; passage (of time); stream; current; course of events" },
        げんち: { 読み方: ['現地'], form: '名詞', 意味: "actual place; actual location" },
        かち: { 読み方: ['価値'], form: '名詞', 意味: "value; worth; merit" },
        がめん: { 読み方: ['画面'], form: '名詞', 意味: "screen (of a TV, computer, etc.)" },
        りよう: { 読み方: ['利用'], form: '名詞、する動詞、他動詞', 意味: "use; utilization" },
        きょだい: { 読み方: ['巨大'], form: 'な形容詞、名詞', 意味: "huge; gigantic; enormous" },
        ひっし: { 読み方: ['必死'], form: 'な形容詞、の形容詞', 意味: "frantic; desparate" },
        さいど: { 読み方: ['再度'], form: '副詞、名詞', 意味: "a second time; again; once more; twice" },
    },

    yomerabaii: {
        昆虫: { 読み方: ['こんちゅう'], form: '名詞、の形容詞', 意味: "insect; bug" },
        箱: { 読み方: ['はこ／ーばこ'], form: '名詞', 意味: "box; case; packge" },
        採集: { 読み方: ['さいしゅう'], form: '名詞、する動詞、他動詞', 意味: "collecting; gathering" },
        満足: { 読み方: ['まんぞく'], form: '名詞、な形容詞、する動詞', 意味: "satisfaction; contentment; sufficient; satisfactory; enough; adequate" },
        同級生: { 読み方: ['どうきゅうせい'], form: '名詞', 意味: "classmate" },
        本格的: { 読み方: ['ほんかくてき'], form: 'な形容詞', 意味: "genuine; real; authentic; full-scale; proper; full-fledged" },
        悪気: { 読み方: ['わるぎ'], form: '名詞', 意味: "ill will; malice; evil intent" },
        文句: { 読み方: ['もんく'], form: '名詞', 意味: "complaint; objection; grumbling" },
        指: { 読み方: ['ゆび'], form: '名詞', 意味: "finger; toe" },
        冗談: { 読み方: ['じょうだん'], form: '名詞', 意味: "joke; jest; funny story" },
        動作: { 読み方: ['どうさ'], form: '名詞、する動詞、自動詞', 意味: "movement (of the body); motion; behavior; operation (of a machine, software, etc.)" },
        確認: { 読み方: ['かくにん'], form: '名詞、する動詞、他動詞', 意味: "confirmation; verification; validation" },
        作業: { 読み方: ['さぎょう'], form: '名詞、する動詞', 意味: "work; operatin; manufacturing; fatigue duty" },
        冷蔵庫: { 読み方: ['れいぞうこ'], form: '名詞', 意味: "fridge" },
        警察: { 読み方: ['けいさつ'], form: '名詞', 意味: "police" },
        真剣: { 読み方: ['しんけん'], form: 'な形容詞', 意味: "serious; earnest" },
        飛び出す: { 読み方: ['とびだす'], form: '五段動詞、自動詞', 意味: "to jump out; to rush out; to fly out" },
        商店街: { 読み方: ['しょうてんがい'], form: '名詞', 意味: "shopping district; shopping street; downtown" },
    },
}

export default unit3_2;