const unit3_1 = {
    tango: {
        約束: { 読み方: ['やくそく'], form: '名詞、する動詞', 意味: "promise; agreement; arrangement; one's word" },
        我々: { 読み方: ['われわれ'], form: '代名詞', 意味: "we" },
        仲: { 読み方: ['なか'], form: '名詞', 意味: "relation; relationship" },
        ぎくしゃく: { 読み方: ['ギクシャク'], form: '副詞、と副詞、する動詞', 意味: "awkward (movements, speech, etc.); jerky; stiff" },
        恋人: { 読み方: ['こいびと'], form: '名詞', 意味: "lover; sweetheart; signficant other" },
        げっそり: { 読み方: [''], form: 'と副詞、する動詞', 意味: "suddenly (losing a lot of weight); becoming very thin; to be disheartented; to be discouraged" },
        やつれる: { 読み方: [''], form: '一段動詞、自動詞', 意味: "to become worn out (illness, worry, etc.); to become emaciated; to become haggard" },
        諦める: { 読み方: ['あきらめる'], form: '一段動詞、他動詞', 意味: "to give up; to abandon (hope, plans); to resign oneself (to)" },
        体を壊す: { 読み方: ['からだをこわす'], form: '表現、五段動詞', 意味: "to harm one's health" },
        忠告: { 読み方: ['ちゅうこく'], form: '名詞、する動詞、の形容詞、他動詞', 意味: "advice; warning" },
        元に戻る: { 読み方: ['もとにもどる'], form: '表現、五段動詞', 意味: "to return back to normal; to revert to the starting point; to go back to how it was" },
        永遠: { 読み方: ['えいえん'], form: 'な形容詞、の形容詞、名詞', 意味: "eternity; immortality" },
        別れる: { 読み方: ['わかれる'], form: '一段動詞、自動詞', 意味: "to break up; to divorce; to part from; to part with" },
        結局: { 読み方: ['けっきょく'], form: '副詞、名詞、の形容詞', 意味: "after all; in the end; ultimately; conclusion" },
        運命: { 読み方: ['うんめい'], form: '名詞、の形容詞', 意味: "fate; destiny" },
        一生: { 読み方: ['いっしょう'], form: '名詞、の形容詞、副詞', 意味: "whole life; a lifetime; all through life" },
        存在: { 読み方: ['そんざい'], form: '名詞、する動詞、の形容詞、自動詞', 意味: "existence; being" },
        無: { 読み方: ['む'], form: '名詞', 意味: "nothing" },
        空白: { 読み方: ['くうはく'], form: '名詞', 意味: "blank space; vacuum; blank; void" },
        周辺: { 読み方: ['しゅうへん'], form: '名詞', 意味: "in the area of; in the vicinity of" },
        目が行く: { 読み方: ['めがいく／めがゆく'], form: '表現、五段動詞', 意味: "to look toward; to have one's eyes drawn towards something" },
        何の前触れもなく: { 読み方: ['なんのまえぶれもなく'], form: '表現', 意味: "without any warning" },
        前触れ: { 読み方: ['まえぶれ'], form: '名詞、する動詞、自動詞', 意味: "advance warning; previous notice" },
        勤める: { 読み方: ['（〜に）つとめる'], form: '一段動詞、他動詞', 意味: "to work (for); to be employed (at)" },
        出張: { 読み方: ['しゅっちょう'], form: '名詞、する動詞、自動詞', 意味: "business trip; official trip" },
        先: { 読み方: ['〜さき'], form: '名詞', 意味: "point; tip; front; first; before; ahead (of); previous" },
        突然: { 読み方: ['とつぜん'], form: 'の形容詞、な形容詞、副詞', 意味: "abrupt; sudden; unexpected" },
        家にこもる: { 読み方: ['いえにこもる'], form: '表現、五段動詞、自動詞', 意味: "to stay at home; to seclude oneself" },
        来る日も来る日も: { 読み方: ['くるひもくるひも'], form: '表現', 意味: "day after day; every single day" },
        泣き暮らす: { 読み方: ['なきくらす'], form: '五段動詞、他動詞', 意味: "to spend one's days in tears and sorrow" },
    },

    kaku: {
        やくそく: { 読み方: ['約束'], form: '名詞、する動詞', 意味: "promise; contract" },
        ころ: { 読み方: ['頃'], form: '名詞、副詞、接尾辞', 意味: "(approximate) time; around; about; toward; time of year" },
        こいびと: { 読み方: ['恋人'], form: '名詞', 意味: "lover; sweetheart; significant other" },
        わかれる: { 読み方: ['別れる'], form: '一段動詞、自動詞', 意味: "to part; to part from; to break up" },
        うんめい: { 読み方: ['運命'], form: '名詞、の形容詞', 意味: "destiny; fate" },
        いっしょう: { 読み方: ['一生'], form: '名詞、の形容詞、副詞', 意味: "whole life; a lifetime; (the only, the greatest, etc.) of one's life" },
        ちょくご: { 読み方: ['直後'], form: '名詞、副詞', 意味: "immediately folllowing" },
        とつぜん: { 読み方: ['突然'], form: '名詞、な形容詞、副詞', 意味: "abrupt; sudden; unexpected" },
    },

    yomerabaii: {
        我々: { 読み方: ['われわれ'], form: '代名詞', 意味: "we" },
        仲: { 読み方: ['なか'], form: '名詞', 意味: "relation; relationship" },
        酒場: { 読み方: ['さかば'], form: '名詞', 意味: "bar; pub; tavern" },
        壊す: { 読み方: ['こわす'], form: '五段動詞、他動詞', 意味: "to break; to destroy" },
        忠告: { 読み方: ['ちゅうこく'], form: '名詞、する動詞、の形容詞、他動詞', 意味: "advice; warning" },
        永遠: { 読み方: ['えいえん'], form: '名詞、の形容詞、な形容詞', 意味: "eternity" },
        結局: { 読み方: ['けっきょく'], form: '副詞、名詞、の形容詞', 意味: "after all; in the end; ultimately; conclusion; end" },
        存在: { 読み方: ['そんざい'], form: '名詞、する動詞、の形容詞、自動詞', 意味: "existence; being" },
        空白: { 読み方: ['くうはく'], form: '名詞、な形容詞、の形容詞', 意味: "vacuum; blank; void; blank space (in documents)" },
        周辺: { 読み方: ['しゅうへん'], form: '名詞', 意味: "circumference; outskirts; in the area of; in the vicinity of" },
        前触れ: { 読み方: ['まえぶれ'], form: '名詞、する動詞、自動詞', 意味: "advance warning; previous notice; prior announcement" },
        出張: { 読み方: ['しゅっちょう'], form: '名詞、する動詞、自動詞', 意味: "business trip" },
        札幌: { 読み方: ['さっぽろ'], form: '名詞', 意味: "Sapporo (city in Hokkaido)" },
    },
}

export default unit3_1;