const kanji = {
    tango: {
        // Unit 1_1
        面する: { 読み方: ['（〜に）めんする'], form: 'する動詞', 意味: "to face~" },
        今どき: { 読み方: ['いまどき'], form: '名詞、副詞', 意味: "nowadays" },
        珍しい: { 読み方: ['めずらしい'], form: 'イ形容詞', 意味: "unusual; rare; curious" },
        壁: { 読み方: ['かべ'], form: '名詞', 意味: "wall" },
        立て掛ける: { 読み方: ['（〜に）たてかける'], form: '他動詞', 意味: "ot lean (something against~)" },
        無造作: { 読み方: ['むぞうさ'], form: 'ナ形容詞', 意味: "casual; careless" },
        張り紙: { 読み方: ['はりがみ'], form: '名詞', 意味: "（＝貼り紙）a sign, poster" },
        可能: { 読み方: ['かのう'], form: 'ナ形容詞、名詞', 意味: "possible; potential; feasible" },
        断り書き: { 読み方: ['ことわりガキ'], form: '名詞', 意味: "disclaimer" },
        込める: { 読み方: ['こめる'], form: '一段動詞、他動詞', 意味: "to infuse; load; put" },
        電源コード: { 読み方: ['でんげんコード'], form: '名詞', 意味: "power cord" },
        延びる: { 読み方: ['のびる'], form: '一段動詞、自動詞', 意味: "to extend;" },
        切れる: { 読み方: ['（スイッチが）きれる'], form: '一段動詞、自動詞', 意味: "to be cut; to stop working; to go dead; " },
        ところどころ: { 読み方: [''], form: '副詞、名詞', 意味: "here and there; in places" },
        サビつく: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to rust; to beocme rusty" },
        泥: { 読み方: ['どろ'], form: '名詞', 意味: "mud" },
        泥がはねる: { 読み方: ['どろがはねる'], form: '表現、一段動詞、他動詞', 意味: "to splash with mud" },
        側面: { 読み方: ['そくめん'], form: '名詞', 意味: "side" },
        汚れる: { 読み方: ['よごれる'], form: '一段動詞、自動詞', 意味: "to get dirty; to become dirty" },
        表面: { 読み方: ['ひょうめん'], form: '名詞', 意味: "surface; exterior" },
        プリント: { 読み方: [''], form: '名詞', 意味: "printed images/texts" },
        以前: { 読み方: ['いぜん'], form: '名詞、副詞', 意味: "ago; since; before; previous" },
        恐れがある: { 読み方: ['おそれがある'], form: '表現', 意味: "there is a danger (possibility) that..." },
        明記: { 読み方: ['めいき'], form: '名詞、スル動詞、他動詞', 意味: "clear writing; specification" },
        解釈: { 読み方: ['かいしゃく'], form: '名詞、スル動詞、他動詞', 意味: "interpretation; to interpret (the meaning);" },
        持ち去る: { 読み方: ['もちさる'], form: '五段動詞', 意味: "to take away; to carry away" },
        やつ: { 読み方: [''], form: '名詞、代名詞', 意味: "guy; he/him; [vulgar version of] a \"person\" or a \"thing\"" },
        一度や二度ではない: { 読み方: ['いちどやにどではない'], form: '表現', 意味: "not just once or twice = many times" },
        持ち主: { 読み方: ['もちぬし'], form: '名詞', 意味: "owner" },
        行為: { 読み方: ['こうい'], form: '名詞', 意味: "action; act; deed; conduct" },
        裏側: { 読み方: ['うらがわ'], form: '名詞', 意味: "the reverse side; other side" },
        廊下: { 読み方: ['ろうか'], form: '名詞', 意味: "hallway; corridor" },
        ほっとく: { 読み方: [''], form: '表現', 意味: "＝（人を）ほうっておくto leave someone alone" },
        ある種: { 読み方: ['あるしゅの'], form: '名詞、ノ形容詞', 意味: "a sort of~; certain; some kind of" },
        気に入る: { 読み方: ['きにいる'], form: '表現、五段動詞', 意味: "to like; come into someone's favor" },
        越す: { 読み方: ['こす'], form: '五段動詞、尊敬語', 意味: "to go; to come" },
        瓶: { 読み方: ['びん'], form: '名詞', 意味: "bottle" },
        容器: { 読み方: ['ようき'], form: '名詞', 意味: "container; vessel; packaging" },
        塩: { 読み方: ['しお'], form: '名詞', 意味: "salt" },
        見かける: { 読み方: ['みかける'], form: '一段動詞、他動詞', 意味: "to see; come across; to catch sight of; to (happen to) see" },
        透明: { 読み方: ['とうめい'], form: 'ナ形容詞', 意味: "transparent; clear" },
        蓋: { 読み方: ['ふた'], form: '名詞', 意味: "cover; lid; cap" },
        穴: { 読み方: ['あな'], form: '名詞', 意味: "hole" },
        振る: { 読み方: ['ふる'], form: '五段動詞、他動詞', 意味: "to wave; to shake" },
        山盛り: { 読み方: ['やまもり'], form: '名詞、ノ形容詞', 意味: "heap" },
        ロビー: { 読み方: [''], form: '名詞', 意味: "lobby" },
        奥: { 読み方: ['おく'], form: '名詞', 意味: "(further in) back" },
        便座: { 読み方: ['べんざ'], form: '名詞', 意味: "toilet seat" },
        目撃: { 読み方: ['もくげき'], form: '名詞、スル動詞、他動詞', 意味: "witnessing; observing; sighting" },
        事実: { 読み方: ['じじつ'], form: '副詞、名詞', 意味: "fact; truth; reality" },
        足跡: { 読み方: ['あしあと'], form: '名詞', 意味: "footprint" },
        後を絶たない: { 読み方: ['あしをたたない'], form: '表現、イ形容詞', 意味: "never ceasing; never ending; endless" },
        事態: { 読み方: ['じたい'], form: '名詞', 意味: "state (of affairs/things); circumstances" },
        特有: { 読み方: ['とくゆう'], form: 'の形容詞、な形容詞', 意味: "characteristic (of); peculiar (of)" },
        比較的: { 読み方: ['ひかくてき'], form: '副詞', 意味: "comparatively; relatively" },
        謎: { 読み方: ['なぞ'], form: '名詞', 意味: "mystery; riddle" },
        板壁: { 読み方: ['いたかべ'], form: '名詞', 意味: "wooden wall" },
        丹念: { 読み方: ['たんねん'], form: 'な形容詞、名詞', 意味: "careful; patient; meticulous" },
        色あせる: { 読み方: ['いろあせる'], form: '一段動詞、自動詞', 意味: "to fade in color" },
        潜む: { 読み方: ['ひそむ'], form: '五段動詞、自動詞', 意味: "to lurk; to be hidden; to be concealed; to be dormant" },
        無法地帯: { 読み方: ['むほうちたい'], form: '名詞', 意味: "lawless area; lawless district" },
        醤油差し: { 読み方: ['しょうゆさし'], form: '名詞', 意味: "soy sauce bottle" },
        爪楊枝: { 読み方: ['つまようじ'], form: '名詞', 意味: "toothpick" },
        ガラス製: { 読み方: ['ガラスせい'], form: 'の形容詞', 意味: "(made of) glass" },
        塞ぐ: { 読み方: ['ふさぐ'], form: '五段動詞、他動詞', 意味: "to block; cover; clog up" },
        金属製: { 読み方: ['きんぞくせい'], form: '名詞、の形容詞', 意味: "(made from) metal; metallic" },
        常人: { 読み方: ['じょうじん'], form: '名詞', 意味: "ordinary person" },

        // Unit 1_2
        峠: { 読み方: ['とうげ'], form: '名詞', 意味: "mountain peak" },
        越える: { 読み方: ['こえる'], form: '一段動詞、他動詞', 意味: "to surpass; to cross over" },
        峠を越える: { 読み方: ['とうげをこえる'], form: '表現、一段動詞、他動詞', 意味: "to pass the peak; to be over the worse" },
        険しい: { 読み方: ['けわしい'], form: 'い形容詞', 意味: "steep; grim" },
        曲がりくねる: { 読み方: ['まがりくねる'], form: '五段動詞、自動詞', 意味: "to turn and twist; to bend many times; to zigzag" },
        谷: { 読み方: ['たに'], form: '名詞', 意味: "valley" },
        ハンドル: { 読み方: [''], form: '名詞', 意味: "steering wheel" },
        操作: { 読み方: ['そうさ'], form: '名詞、する動詞、他動詞', 意味: "operation; handling" },
        誤る: { 読み方: ['あやまる'], form: '五段動詞、他動詞', 意味: "to make a mistake (in); to commit an error; to be wrong" },
        一瞬にして: { 読み方: ['いっしゅんにして'], form: '表現、副詞', 意味: "in an instant; in a moment; instantaneously" },
        転落: { 読み方: ['てんらく'], form: '名詞、する動詞、自動詞', 意味: "fall; tumble; plunge" },
        ジェットコースター: { 読み方: [''], form: '名詞', 意味: "roller coaster" },
        恐怖: { 読み方: ['きょうふ'], form: '名詞、する動詞', 意味: "fear; dread; dismay; terror; horror" },
        快感: { 読み方: ['かいかん'], form: '名詞', 意味: "pleasant feeling; pleasant sensation; pleasure" },
        はし: { 読み方: ['（〜の）はし'], form: '名詞', 意味: "end; tip; edge; margin" },
        標識: { 読み方: ['ひょうしき'], form: '名詞', 意味: "sign; mark; flag" },
        発見: { 読み方: ['はっけん'], form: '名詞、する動詞、他動詞', 意味: "discovery; detection; finding" },
        鮮やか: { 読み方: ['あざやか'], form: 'な形容詞', 意味: "vivid; bright; vibrant; skillful; brilliant" },
        命知らず: { 読み方: ['いのちしらず'], form: '名詞、の形容詞、な形容詞', 意味: "recklessness; daredevil; rashness" },
        わき: { 読み方: ['（〜の）わき'], form: '名詞', 意味: "side; beside" },
        プレート: { 読み方: [''], form: '名詞', 意味: "plate" },
        プラスチック: { 読み方: [''], form: '名詞', 意味: "plastic" },
        想像: { 読み方: ['そうぞう'], form: '名詞、する動詞、他動詞', 意味: "imagination; supposition" },
        際: { 読み方: ['（〜の）きわ／ぎわ'], form: '名詞、接尾辞', 意味: "edge; verge" },
        敷設: { 読み方: ['ふせつ'], form: '名詞、する動詞、他動詞', 意味: "to lay (a railroad, pipes, naval mines, etc.)" },
        同居: { 読み方: ['どうきょ'], form: '名詞、する動詞、自動詞', 意味: "living together; coexistence" },
        端的: { 読み方: ['たんてき'], form: 'な形容詞', 意味: "straightfoward; concise; plain; direct; frank" },
        塗料: { 読み方: ['とりょう'], form: '名詞', 意味: "paint" },

        // Unit 2_1
        滞在: { 読み方: ['たいざい'], form: '名詞、する動詞、自動詞', 意味: "stay" },
        駐車場: { 読み方: ['ちゅうしゃじょう'], form: '名詞', 意味: "parking lot; parking garage" },
        白人: { 読み方: ['はくじん'], form: '名詞', 意味: "caucasian" },
        中年男: { 読み方: ['ちゅうねんおとこ'], form: '名詞', 意味: "middle-aged man" },
        呼び止める: { 読み方: ['よびとめる'], form: '一段動詞、他動詞', 意味: "to (call to) stop [someone]" },
        日焼けする: { 読み方: ['ひやけする'], form: '名詞、する動詞、自動詞', 意味: "sunburn; suntan; become discolored from the sun" },
        簡素: { 読み方: ['かんそ'], form: 'な形容詞、名詞', 意味: "modest; simple; plain" },
        衣服: { 読み方: ['いふく'], form: '名詞', 意味: "clothes" },
        服装: { 読み方: ['ふくそう'], form: '名詞', 意味: "garments; attire" },
        市民: { 読み方: ['しみん'], form: '名詞', 意味: "citizen; city inhabitant; townspeople" },
        見分けがつかない: { 読み方: ['みわけがつかない'], form: '表現', 意味: "indistinguishable" },
        見分け: { 読み方: ['みわけ'], form: '名詞', 意味: "distinction" },
        見分ける: { 読み方: ['みわける'], form: '一段動詞、他動詞', 意味: "to distinguish; to recognize; to tell apart; to differentiate" },
        おおよそ: { 読み方: [''], form: '副詞', 意味: "about; roughly; approximately; generally" },
        想像がつく: { 読み方: ['そうぞうがつく'], form: '表現、五段動詞', 意味: "ot be imaginable; to be conceivable" },
        お腹が減る: { 読み方: ['おなかがへる'], form: '表現、五段動詞', 意味: "to become hungry" },
        小銭: { 読み方: ['こぜに'], form: '名詞', 意味: "small change; coins" },
        呼びかける: { 読み方: ['よびかける'], form: '一段動詞、他動詞', 意味: "to address; call (for help)" },
        金額: { 読み方: ['きんがく'], form: '名詞', 意味: "amount of money; sum of money" },
        限定: { 読み方: ['げんてい'], form: '名詞、する動詞、他動詞', 意味: "limit; restriction" },
        援助: { 読み方: ['えんじょ'], form: '名詞、する動詞、他動詞', 意味: "assistance; aid; support" },
        求める: { 読み方: ['もとめる'], form: '一段動詞、他動詞', 意味: "to want; to wish for; to request" },
        焼く: { 読み方: ['やく'], form: '五段動詞、他動詞', 意味: "to burn; to grill; to heat; to heat up" },
        匂い: { 読み方: ['におい'], form: '名詞', 意味: "odor; scent; aura" },
        漂う: { 読み方: ['ただよう'], form: '五段動詞、自動詞', 意味: "to drift; to float; to waft (e.g. a scent)" },
        つらい: { 読み方: [''], form: 'い形容詞', 意味: "painful; bitter; heart-breaking; difficult (emotinally)" },
        同情: { 読み方: ['どうじょう'], form: '名詞、する動詞、自動詞', 意味: "sympathy; compassion; pity" },
        確か: { 読み方: ['たしか'], form: 'な形容詞、名詞', 意味: "sure; certain; positive; definite; reliable; trustworthy" },
        全く: { 読み方: ['まったく'], form: '副詞、の形容詞', 意味: "really; truly; entirely; completely; good grief" },
        訴える: { 読み方: ['うったえる'], form: '一段動詞、他動詞', 意味: "to bring to (someone's attention); to appeal to (reason, emotions, etc.); to play on (one's sympathies); to sue" },
        企画力: { 読み方: ['きかくりょく'], form: '名詞', 意味: "planning ability" },
        素直: { 読み方: ['すなお'], form: 'な形容詞', 意味: "honest; frank; upfront (about one's feelings)" },
        感心: { 読み方: ['かんしん'], form: '名詞、する動詞', 意味: "admiration; being impressed" },
        にこりともせずに: { 読み方: [''], form: '表現', 意味: "with no smile" },
        突っ込む: { 読み方: ['つっこむ'], form: '五段動詞、他動詞', 意味: "to thrust (something) into (something); to cram; to stuff; to shove" },
        音を立てる: { 読み方: ['おとをたてる'], form: '表現、一段動詞', 意味: "to make a sound" },
        浮かぶ: { 読み方: ['うかぶ'], form: '五段動詞', 意味: "to float; to be suspended" },
        考えが浮かぶ: { 読み方: ['かんがえがうかぶ'], form: '表現', 意味: "to have an idea; idea occurs to [person]" },
        手遅れ: { 読み方: ['ておくれ（だ／になる）'], form: '名詞', 意味: "being too late; losing one's final chance" },
        街角: { 読み方: ['まちかど'], form: '名詞', 意味: "street corner" },
        微か: { 読み方: ['かすか'], form: 'な形容詞', 意味: "slight; faint; subtle" },

        // Unit 2_2
        教訓: { 読み方: ['きょうくん'], form: '名詞、する動詞、他動詞', 意味: "lesson, teachings, moral" },
        ある程度: { 読み方: ['あるていど'], form: '表現、の形容詞、副詞', 意味: "to some extent; to a certain extent" },
        領域: { 読み方: ['りょういき'], form: '名詞、の形容詞', 意味: "area; domain; region" },
        単に: { 読み方: ['たんに'], form: '副詞', 意味: "simply; merely; only" },
        義務的: { 読み方: ['ぎむてき'], form: 'な形容詞', 意味: "obligatory; mandatory" },
        具体的: { 読み方: ['ぐたいてき'], form: 'な形容詞', 意味: "specific; substantial; concrete; definite" },
        率直: { 読み方: ['そっちょく'], form: 'な形容詞、名詞', 意味: "straightforward; frank; direct; candid" },
        提出: { 読み方: ['ていしゅつ'], form: '名詞、する動詞、他動詞', 意味: "turning in; submission (of an application, report, etc.)" },
        他人事: { 読み方: ['たにんごと'], form: '名詞', 意味: "someone else's problem; other people's affairs" },
        事情: { 読み方: ['じじょう'], form: '名詞', 意味: "state of affairs; circumstances; conditions; situation" },
        反射的: { 読み方: ['はんしゃてき'], form: 'な形容詞', 意味: "reflexive; reflecting" },
        わずか: { 読み方: [''], form: 'な形容詞', 意味: "a little; a few; slight; small amount; only; just; merely" },
        隅: { 読み方: ['すみ'], form: '名詞、接尾詞', 意味: "corner; nook" },
        接す: { 読み方: ['せっす［＝coll.接する］'], form: 'する動詞、自動し、他動詞', 意味: "to treat someone; to come in contact with; to take care of; to look after; to connect" },
        接し方: { 読み方: ['（〜との）せっしかた'], form: '名詞', 意味: "the way someone treats (people)" },
        蝶: { 読み方: ['ちょう'], form: '名詞', 意味: "butterfly" },
        担任教師: { 読み方: ['たんにんきょうし'], form: '名詞', 意味: "class teacher" },
        胸: { 読み方: ['むね'], form: '名詞', 意味: "chest; heart; mind; feelings" },
        突き刺さる: { 読み方: ['つきささる'], form: '五段動詞、自動詞', 意味: "to stick into; to pierce" },
        チクリと: { 読み方: [''], form: '副詞', 意味: "prickling; stinging; biting" },
        痛む: { 読み方: ['いたむ'], form: '五段動詞、自動詞', 意味: "to hurt; to ache; to feel a pain" },
        当時: { 読み方: ['とうじ'], form: '名詞、副詞', 意味: "at that time; in those days" },
        いじめる: { 読み方: [''], form: '一段動詞、他動詞', 意味: "to ill-treat; to bully; to torment; to pick on; to tease" },
        避ける: { 読み方: ['さける'], form: '一段動詞、他動詞', 意味: "to avoid (physical contact with); to avoid (situation)" },
        いじめ: { 読み方: [''], form: '名詞', 意味: "bullying; teasing" },
        手を焼く: { 読み方: ['てをやく'], form: '表現、五段動詞', 意味: "do not know what to do with; to be at a loss with; to have difficulty with" },
        うなずき返す: { 読み方: ['うなずきかえす'], form: '五段動詞、自動詞', 意味: "to nod back" },
        今更: { 読み方: ['いまさら'], form: '副詞', 意味: "now (after such a long time); it's too late (to~)" },
        生意気: { 読み方: ['なまいき'], form: 'な形容詞、名詞', 意味: "impertinent; cheeky; impudent; audacious; cocky" },
        クモの巣: { 読み方: ['クモのす'], form: '名詞', 意味: "spider's web" },
        引っ掛かる: { 読み方: ['ひっかかる'], form: '五段動詞、自動詞', 意味: "to get stuck; to get caught" },
        はらう: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to brush off; to slap away" },
        にこにこ: { 読み方: [''], form: '副詞、する動詞', 意味: "smilingly; with a friendly grin" },
        出来事: { 読み方: ['できごと'], form: '名詞', 意味: "incident; affair; happening; event" },
        日記: { 読み方: ['にっき'], form: '名詞', 意味: "diary; journal" },
        花丸: { 読み方: ['はなまる'], form: '名詞', 意味: "encircled flower seal" },
        返却: { 読み方: ['へんきゃく'], form: '名詞、する動詞、他動詞', 意味: "return of something; repayment" },
        息が詰まる: { 読み方: ['いきがつまる'], form: '表現、五段動詞', 意味: "to feel suffocate; to choke; to have trouble breathing" },
        思いやる: { 読み方: ['おもいやる'], form: '五段動詞、他動詞', 意味: "to be considerate; to sympathise with ［n.思いやり］" },
        理論的: { 読み方: ['りろんてき'], form: 'な形容詞', 意味: "theoretical" },
        響く: { 読み方: ['ひびく'], form: '五段動詞、自動詞', 意味: "to resound; to have an effect; to make an impression" },
        基本: { 読み方: ['きほん'], form: '名詞、の形容詞', 意味: "basics; basis; foundation; fundamentals" },

        // Unit 2_2 Sankou
        漠然: { 読み方: ['ばくぜん'], form: 'たる形容詞、と副詞', 意味: "ambiguous; obscure; vague" },
        思い巡らせる: { 読み方: ['おもいめぐらせる'], form: '一段動詞', 意味: "to think over; to speculate; to mull over" },
        あからさま: { 読み方: [''], form: 'な形容詞', 意味: "obviously; overtly; openly; direct; straightforward" },
        決め込む: { 読み方: ['きめこむ'], form: '五段動詞、他動詞', 意味: "to persist in doing; to do intentionally" },
        収まる: { 読み方: ['おさまる'], form: '五段動詞、自動詞', 意味: "to be settled; to calm down; to subside" },
        子供ながらに: { 読み方: ['こどもながらに'], form: '表現', 意味: "even as a child" },
        一連: { 読み方: ['いちれん'], form: '名詞、のけいようし', 意味: "series; a series of" },
        意気揚々: { 読み方: ['いきようよう'], form: 'たる形容詞、と副詞', 意味: "trimphant(ly), in high and proud spirits" },
        決めつける: { 読み方: ['きめつける'], form: '一段動詞、他動詞', 意味: "to stereotype; to decide prematurely" },
        常に: { 読み方: ['つねに'], form: '副詞', 意味: "always; constantly" },
        
        // Unit 3_1

        約束: { 読み方: ['やくそく'], form: '名詞、する動詞', 意味: "promise; agreement; arrangement; one's word" },
        我々: { 読み方: ['われわれ'], form: '代名詞', 意味: "we" },
        仲: { 読み方: ['なか'], form: '名詞', 意味: "relation; relationship" },
        ぎくしゃく: { 読み方: ['ギクシャク'], form: '副詞、と副詞、する動詞', 意味: "awkward (movements, speech, etc.); jerky; stiff" },
        恋人: { 読み方: ['こいびと'], form: '名詞', 意味: "lover; sweetheart; signficant other" },
        げっそり: { 読み方: [''], form: 'と副詞、する動詞', 意味: "suddenly (losing a lot of weight); becoming very thin; to be disheartented; to be discouraged" },
        やつれる: { 読み方: [''], form: '一段動詞、自動詞', 意味: "to become worn out (illness, worry, etc.); to become emaciated; to become haggard" },
        諦める: { 読み方: ['あきらめる'], form: '一段動詞、他動詞', 意味: "to give up; to abandon (hope, plans); to resign oneself (to)" },
        体を壊す: { 読み方: ['からだをこわす'], form: '表現、五段動詞', 意味: "to harm one's health" },
        忠告: { 読み方: ['ちゅうこく'], form: '名詞、する動詞、の形容詞、他動詞', 意味: "advice; warning" },
        元に戻る: { 読み方: ['もとにもどる'], form: '表現、五段動詞', 意味: "to return back to normal; to revert to the starting point; to go back to how it was" },
        永遠: { 読み方: ['えいえん'], form: 'な形容詞、の形容詞、名詞', 意味: "eternity; immortality" },
        別れる: { 読み方: ['わかれる'], form: '一段動詞、自動詞', 意味: "to break up; to divorce; to part from; to part with" },
        結局: { 読み方: ['けっきょく'], form: '副詞、名詞、の形容詞', 意味: "after all; in the end; ultimately; conclusion" },
        運命: { 読み方: ['うんめい'], form: '名詞、の形容詞', 意味: "fate; destiny" },
        一生: { 読み方: ['いっしょう'], form: '名詞、の形容詞、副詞', 意味: "whole life; a lifetime; all through life" },
        存在: { 読み方: ['そんざい'], form: '名詞、する動詞、の形容詞、自動詞', 意味: "existence; being" },
        無: { 読み方: ['む'], form: '名詞', 意味: "nothing" },
        空白: { 読み方: ['くうはく'], form: '名詞', 意味: "blank space; vacuum; blank; void" },
        周辺: { 読み方: ['しゅうへん'], form: '名詞', 意味: "in the area of; in the vicinity of" },
        目が行く: { 読み方: ['めがいく／めがゆく'], form: '表現、五段動詞', 意味: "to look toward; to have one's eyes drawn towards something" },
        何の前触れもなく: { 読み方: ['なんのまえぶれもなく'], form: '表現', 意味: "without any warning" },
        前触れ: { 読み方: ['まえぶれ'], form: '名詞、する動詞、自動詞', 意味: "advance warning; previous notice" },
        勤める: { 読み方: ['（〜に）つとめる'], form: '一段動詞、他動詞', 意味: "to work (for); to be employed (at)" },
        出張: { 読み方: ['しゅっちょう'], form: '名詞、する動詞、自動詞', 意味: "business trip; official trip" },
        先: { 読み方: ['〜さき'], form: '名詞', 意味: "point; tip; front; first; before; ahead (of); previous" },
        突然: { 読み方: ['とつぜん'], form: 'の形容詞、な形容詞、副詞', 意味: "abrupt; sudden; unexpected" },
        家にこもる: { 読み方: ['いえにこもる'], form: '表現、五段動詞、自動詞', 意味: "to stay at home; to seclude oneself" },
        来る日も来る日も: { 読み方: ['くるひもくるひも'], form: '表現', 意味: "day after day; every single day" },
        泣き暮らす: { 読み方: ['なきくらす'], form: '五段動詞、他動詞', 意味: "to spend one's days in tears and sorrow" },

        // Unit 3_1 Sankou
        酒場: { 読み方: ['さかば'], form: '名詞', 意味: "tavern; bar; pub" },
        飲んだくれる: { 読み方: ['のんだくれる'], form: '一段動詞、自動詞', 意味: "to get dead drunk; to get blind drunk" },
        片を付ける: { 読み方: ['かたをつける'], form: '表現、一段動詞', 意味: "to put an end to~; to settle (a problem)" },
        云々: { 読み方: ['うんぬん'], form: '表現', 意味: "and so on; and so forth; et cetera" },
        見据える: { 読み方: ['みすえる'], form: '一段動詞、他動詞', 意味: "to stare fixedly at; to fix one's gaze on; to make sure of; to set one's eyes on (e.g. the future); to focus on" },
        偏狭: { 読み方: ['へんきょう'], form: 'な形容詞、名詞', 意味: "narrow-mindedness" },
        上智大学: { 読み方: ['じょうちだいがく'], form: '場所', 意味: "Sophia University" },
        日本航空: { 読み方: ['にほんこうくう'], form: '名詞', 意味: "Japan Airlines (JAL)" },

        // Unit 3_2
        悔しい: { 読み方: ['くやしい'], form: 'い形容詞', 意味: "frustrated (over a failure, humiliation, or injustice); annoyed; dissapointed; bitter" },
        自慢: { 読み方: ['じまん'], form: '名詞、する動詞、の形容詞、他動詞', 意味: "pride; boast" },
        自信: { 読み方: ['じしん'], form: '名詞、する動詞', 意味: "self-confidence" },
        捕る: { 読み方: ['とる'], form: '五段動詞、他動詞', 意味: "to take; to catch; to capture" },
        実物: { 読み方: ['じつぶつ'], form: '名詞、の形容詞', 意味: "real thing; original; actual" },
        満足: { 読み方: ['まんぞく'], form: '名詞、な形容詞、する動詞', 意味: "satisfaction; sufficient; satisfactory; enough; contentment" },
        ついさっき: { 読み方: [''], form: '表現、の形容詞、副詞', 意味: "just now; a little while back; a short time ago" },
        同級生: { 読み方: ['どうきゅうせい'], form: '名詞', 意味: "classmate" },
        発売: { 読み方: ['はつばい'], form: '名詞、する動詞、他動詞', 意味: "sale; offering for sale; release (for sale); launch (product)" },
        流れ: { 読み方: ['ながれ'], form: '名詞', 意味: "lfow (of a fluid or gas or of people, things); stream; current; course (of events)" },
        本格的: { 読み方: ['ほんかくてき'], form: 'な形容詞', 意味: "genuine; real; authentic; orthodox; full-fledged" },
        現地: { 読み方: ['げんち'], form: '名詞', 意味: "actual place; actual location; the spot; the scene; place where one is currently living" },
        頷く: { 読み方: ['うなずく'], form: '五段動詞、自動詞', 意味: "to nod; to bow one's head in assent" },
        みじめ: { 読み方: [''], form: 'な形容詞', 意味: "miserable; wretched; unhappy; sad" },
        悪気: { 読み方: ['わるぎ'], form: '名詞', 意味: "ill will; malice; evil intent" },
        文句: { 読み方: ['もんく'], form: '名詞', 意味: "complaint; grumbling; objection" },
        情けない: { 読み方: ['なさけない'], form: 'い形容詞', 意味: "miserable; shameful; pathetic" },
        立派: { 読み方: ['りっぱ'], form: 'な形容詞', 意味: "splendid; fine; praiseworthy" },
        ただ: { 読み方: ['ただの［名詞］'], form: 'の形容詞', 意味: "just~; ordinary; common; usual" },
        価値: { 読み方: ['かち'], form: '名詞', 意味: "value; worth; merit" },
        親指: { 読み方: ['おやゆび'], form: '名詞', 意味: "thumb; big toe" },
        人差し指: { 読み方: ['ひとさしゆび'], form: '名詞', 意味: "index finger" },
        間隔: { 読み方: ['かんかく'], form: '名詞', 意味: "space; interval; space character; whitespace" },
        画面: { 読み方: ['がめん'], form: '名詞', 意味: "screen (of a TV, computer, etc.)" },
        拡大: { 読み方: ['かくだい'], form: '名詞、する動詞、他動詞、自動詞', 意味: "magnification; enlargement; expansion; extension" },
        操作: { 読み方: ['そうさ'], form: '名詞、する動詞、他動詞', 意味: "operation; management; handling" },
        冗談: { 読み方: ['じょうだん'], form: '名詞', 意味: "joke;jest; funny story" },
        思わず: { 読み方: ['おもわず〜'], form: '副詞', 意味: "unconsciously; instinctively" },
        つまむ: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to pinch" },
        動作: { 読み方: ['どうさ'], form: '名詞、する動詞', 意味: "movement (of the body); action; motion; operation (of a machine, software, etc.)" },
        もと: { 読み方: ['もとの'], form: 'の形容詞', 意味: "former~; original~" },
        確認: { 読み方: ['かくにん'], form: '名詞、する動詞、他動詞', 意味: "confirmation; verification; validation" },
        利用: { 読み方: ['りよう'], form: '名詞、する動詞、他動詞', 意味: "use; utilization; application" },
        次から次へと: { 読み方: [''], form: '表現', 意味: "one after another" },
        作業: { 読み方: ['さぎょう'], form: '名詞、する動詞', 意味: "work; operation" },
        巨大: { 読み方: ['きょだい'], form: 'な形容詞、名詞', 意味: "huge; gigantic; enormous" },
        級: { 読み方: ['〜きゅう'], form: '名詞、接尾辞', 意味: "class; grade; rank" },
        しばらく: { 読み方: [''], form: '副詞、する動詞', 意味: "for a moment; for a minute; for a while; for some time; for the time being; for now" },
        にんまりと: { 読み方: [''], form: '副詞、と副詞、する動詞', 意味: "with a complacent smile; with a smile of satisfaction" },
        取り出す: { 読み方: ['とりだす'], form: '五段動詞、他動詞', 意味: "to take out; to produce; to fetch; to retrieve" },
        拭く: { 読み方: ['ふく'], form: '五段動詞、他動詞', 意味: "to wipe; to dry" },
        ばったり: { 読み方: ['ばったり会う'], form: '副詞、と副詞', 意味: "unexpectedly (meeting someone); to bump into~" },
        警察: { 読み方: ['けいさつ'], form: '名詞', 意味: "police" },
        真剣: { 読み方: ['しんけん'], form: 'な形容詞', 意味: "serious; earnest" },
        必死: { 読み方: ['ひっし'], form: 'な形容詞、の形容詞', 意味: "frantic; desparate" },
        無駄: { 読み方: ['むだ'], form: 'な形容詞、名詞', 意味: "futility; waste; uselessness; pointlessness" },
        駆ける: { 読み方: ['かける'], form: '一段動詞、自動詞', 意味: "to run; to dash; to race" },
        飛び出す: { 読み方: ['とびだす'], form: '五段動詞、自動詞', 意味: "to jump out; to rush out; to fly out; to appear (suddenly)" },
        商店街: { 読み方: ['しょうてんがい'], form: '名詞', 意味: "shopping district; shopping street; downtown" },
        立ち止まる: { 読み方: ['たちどまる'], form: '五段動詞、自動詞', 意味: "to stop (in one's tracks); to come to a stop; to halt" },
        映る: { 読み方: ['うつる'], form: '五段動詞、自動詞', 意味: "to be reflected; to be projected; to be displayed (on a screen)" },
        こする: { 読み方: [''], form: '五段動詞、他動詞', 意味: "to rub; to scrub; to scrape" },
        再度: { 読み方: ['さいど'], form: '副詞、名詞', 意味: "a second time; again; once more; twice" },
        まくる: { 読み方: ['V[STEM]ーまくる'], form: '五段動詞、補助動詞', 意味: "to V over and over again" },

        //Unit 3_2 Sankou
        自由研究: { 読み方: ['じゆうけんきゅう'], form: '名詞', 意味: "research project (e.g. at school); independent research" },
        昆虫: { 読み方: ['こんちゅう'], form: '名詞、の形容詞', 意味: "insects" },
        標本: { 読み方: ['ひょうほん'], form: '名詞', 意味: "specimen; sample" },
        昆虫採集: { 読み方: ['こんちゅうさいしゅう'], form: '名詞', 意味: "insect collecting" },
        カブトムシ: { 読み方: [''], form: '名詞', 意味: "rhinoceros beetle" },
        クワガタ: { 読み方: [''], form: '名詞', 意味: "stag beetle" },
        アブラゼミ: { 読み方: [''], form: '名詞', 意味: "brown cicada" },
        ミンミンゼミ: { 読み方: [''], form: '名詞', 意味: "robust cicada" },
        アゲハチョウ: { 読み方: [''], form: '名詞', 意味: "swallowtail butterfly" },
        モンシロチョウ: { 読み方: [''], form: '名詞', 意味: "small cabbage white butterfly" },
        オニヤンマ: { 読み方: [''], form: '名詞', 意味: "jumbo dragonfly" },
        シオカラトンボ: { 読み方: [''], form: '名詞', 意味: "common skimmer" },
        バッタ: { 読み方: [''], form: '名詞', 意味: "locust" },
        カマキリ: { 読み方: [''], form: '名詞', 意味: "praying mantis" },
        キリギリス: { 読み方: [''], form: '名詞', 意味: "grasshopper" },
        生体: { 読み方: ['せいたい'], form: '名詞、の形容詞', 意味: "organism; living body" },
        習性: { 読み方: ['しゅうせい'], form: '名詞', 意味: "habit" },
        昆虫図鑑: { 読み方: ['こんちゅうずかん'], form: '名詞', 意味: "encyclopedia of insects" },
        ひとしきり: { 読み方: [''], form: '副詞、の形容詞', 意味: "for some time; for a while; for a period" },
        画用紙: { 読み方: ['がようし'], form: '名詞', 意味: "drawing paper" },
        宝庫: { 読み方: ['ほうこ'], form: '名詞', 意味: "treasure trove; reservoir" },
        みすぼらしい: { 読み方: [''], form: 'い形容詞', 意味: "shabby" },
        あらためて: { 読み方: [''], form: '副詞', 意味: "once again" },
        始業式: { 読み方: ['しぎょうしき'], form: '名詞', 意味: "opening ceremony (of the school term)" },
        ピンチアウト: { 読み方: [''], form: '', 意味: "pinch out (to zoom in)" },
        お手のもの: { 読み方: ['おてのもの'], form: '名詞', 意味: "one's specialty" },
        声をもらす: { 読み方: ['こえをもらす'], form: '表現、五段動詞、他動詞', 意味: "to let out one's voice" },
        試しに: { 読み方: ['ためしに'], form: '副詞', 意味: "for trial; for testing" },
        ピンチイン: { 読み方: [''], form: '', 意味: "pinch in (to zoom out)" },
        声をあげる: { 読み方: ['こえをあげる'], form: '表現、一段動詞', 意味: "to raise one's voice; to shout" },
        しない手はない: { 読み方: ['〜しないてはない'], form: '表現', 意味: "it would be a waste not to" },
        いずれ劣らぬ: { 読み方: ['いずれおとらぬ'], form: '連体詞', 意味: "equally competent" },
        軍団: { 読み方: ['ぐんだん'], form: '名詞', 意味: "army corps" },
        おやつ: { 読み方: [''], form: '名詞', 意味: "mid-afternoon snack" },
        たいらげる: { 読み方: [''], form: '一段動詞、他動詞', 意味: "to eat up (completely)" },
        ぎょうと: { 読み方: [''], form: '副詞、する動詞', 意味: "to be frightened; startled" },
        上がり込む: { 読み方: ['あがりこむ'], form: '五段動詞、自動詞', 意味: "to enter (house)" },
        とぼとぼと歩く: { 読み方: ['とぼとぼと歩く'], form: '表現、五段動詞', 意味: "to plod; trudge" },
        何気なく: { 読み方: ['なにげなく'], form: '表現、副詞', 意味: "unintentionally; involuntarily" },
        はたと: { 読み方: [''], form: '副詞', 意味: "suddenly" },
        同じく: { 読み方: ['おなじく'], form: '副詞、する動詞', 意味: "same; similarly" },
        指でなぞる: { 読み方: ['ゆびでなぞる'], form: '表現、五段動詞、他動詞', 意味: "to run a finger over~" },
        背後から: { 読み方: ['はいごから'], form: '名詞、の形容詞', 意味: "from behind" },
        ばけもの: { 読み方: [''], form: '名詞', 意味: "monster ghost" },

        // Unit 4_1
        記者: { 読み方: ['きしゃ'], form: '名詞', 意味: "reporter; journalist" },
        改姓: { 読み方: ['かいせい'], form: '名詞、する動詞、自動詞', 意味: "change of one's family name" },
        手続き: { 読み方: ['てつづき'], form: '名詞、する動詞', 意味: "procedure; process; proceedings" },
        役所: { 読み方: ['やくしょ'], form: '名詞', 意味: "government office; public office" },
        職員: { 読み方: ['しょくいん'], form: '名詞', 意味: "staff member; employee" },
        名字: { 読み方: ['みょうじ'], form: '名詞', 意味: "surname; family name" },
        念を押す: { 読み方: ['ねんをおす'], form: '表現', 意味: "to remind (something of someone); to call attention; to make sure of; to emphasize" },
        用紙: { 読み方: ['ようし'], form: '名詞', 意味: "blank form" },
        震える: { 読み方: ['ふるえる'], form: '一段動詞、自動詞', 意味: "to shiver; to shake; to quake" },
        当たり前: { 読み方: ['あたりまえ'], form: 'の形容詞、な形容詞、名詞', 意味: "obvious; natural; reasonable" },
        違和感: { 読み方: ['いわかん'], form: '名詞', 意味: "uncomfortable feeling; feeling out of place; sense of discomfort" },
        普段: { 読み方: ['ふだん'], form: '名詞、の形容詞、副詞', 意味: "usual; normal; usually; normal" },
        旧姓: { 読み方: ['きゅうせい'], form: '名詞', 意味: "one's original name" },
        運転免許証: { 読み方: ['うんてんめんきょしょう'], form: '名詞', 意味: "driver's license" },
        窓口: { 読み方: ['まどぐち'], form: '名詞', 意味: "counter window" },
        身分証: { 読み方: ['みぶんしょう'], form: '名詞', 意味: "ID; identification papers" },
        会員証: { 読み方: ['かいいんしょう'], form: '名詞', 意味: "membership card" },
        混乱: { 読み方: ['こんらん'], form: '名詞、する動詞、自動詞', 意味: "confusion; chaos; disorder" },
        思い込み: { 読み方: ['おもいこみ'], form: '名詞', 意味: "wrong impression; assumption; prejudice" },
        上司: { 読み方: ['じょうし'], form: '名詞', 意味: "(one's) superior; (one's) boss" },
        報告: { 読み方: ['ほうこく'], form: '名詞、する動詞、他動詞', 意味: "report; information" },
        勘違い: { 読み方: ['かんちがい'], form: '名詞、する動詞、自動詞', 意味: "misunderstanding; mistaken idea; wrong guess" },
        制度: { 読み方: ['せいど'], form: '名詞、の形容詞', 意味: "system; organization" },
        認める: { 読み方: ['みとめる'], form: '一段動詞、他動詞', 意味: "to recognize; to observe; to notice; to approve; to admit" },
        調査: { 読み方: ['ちょうさ'], form: '名詞、する動詞、他動詞', 意味: "survey; investigation" },
        姉妹: { 読み方: ['しまい'], form: '名詞', 意味: "sisters" },
        求める: { 読み方: ['もとめる'], form: '一段動詞、他動詞', 意味: "to want; to wish for" },
        長男: { 読み方: ['ちょうなん'], form: '名詞', 意味: "eldest son (may be the only son)" },
        末: { 読み方: ['〜のすえ'], form: '副詞、名詞', 意味: "(finally)/at last) after~; at the end of" },
        受け入れる: { 読み方: ['うけいれる'], form: '一段動詞、他動詞', 意味: "to accept; to receive; to agree" },
        食い違い: { 読み方: ['くいちがい'], form: '名詞', 意味: "difference; disagreement; conflict; clash; inconsistency" },
        加わる: { 読み方: ['くわわる'], form: '五段動詞、自動詞', 意味: "to be added; to join in (e.g. a group of friends); to increase; to gain in (e.g. influence); to be applied (e.g. pressure)" },
        意見書: { 読み方: ['いけんしょ'], form: '名詞', 意味: "opinion in writing; written opinion" },
        議会: { 読み方: ['ぎかい'], form: '名詞', 意味: "congress; parliament; diet" },
        都合: { 読み方: ['〜のつごうで'], form: '副詞', 意味: "for reasons of~" },
        議員: { 読み方: ['ぎいん'], form: '名詞', 意味: "member of parliament; member of the Diet" },
        同意: { 読み方: ['どうい'], form: '名詞、する動詞、自動詞', 意味: "agreement; approval; same opinion" },
        死亡: { 読み方: ['しぼう'], form: '名詞、する動詞、自動詞', 意味: "death; dying; mortality" },
        国会: { 読み方: ['こっかい'], form: '名詞', 意味: "National Diet; legislative assembly of Japan" },


        // Unit 4_1 sankou
        婚姻届: { 読み方: ['こんインとどけ'], form: '名詞', 意味: "marriage registration; notification of marriage" },
        欄: { 読み方: ['らん'], form: '名詞、接尾詞', 意味: "field (in a form); section (in a newspaper)" },
        点検: { 読み方: ['てんけん'], form: '名詞、する動詞、多動し', 意味: "to inspect; check; examination" },
        住民票: { 読み方: ['住民票'], form: '名詞', 意味: "certificate of residence" },
        請求: { 読み方: ['せいきゅう'], form: '名詞、する動詞、他動詞', 意味: "to claim; request; demand" },
        押し通す: { 読み方: ['おしとおす'], form: '五段動詞、他動詞', 意味: "to persist in; push through; have one's own way" },
        諭す: { 読み方: ['さとす'], form: '五段動詞、他動詞', 意味: "to admonish; to warn" },
        健康保険証: { 読み方: ['けんこうほけんしょう'], form: '名詞', 意味: "health insurance card" },
        銀行口座: { 読み方: ['ぎんこうこうざ'], form: '名詞', 意味: "bank account" },
        提示: { 読み方: ['ていじ'], form: '名詞、する動詞、他動詞', 意味: "presentation; showing" },
        養子縁組: { 読み方: ['ようしえんぐみ'], form: '名詞', 意味: "adoption (of a person)" },
        煩わしい: { 読み方: ['わずらわしい'], form: 'い形容詞', 意味: "troublesome; annoying" },
        法改正: { 読み方: ['ほうかいせい'], form: '名詞', 意味: "change in law; legal reform" },
        微増: { 読み方: ['びぞう'], form: '名詞、する動詞、自動詞', 意味: "slight increase" },
        就く: { 読み方: ['つく'], form: '五段動詞、自動詞', 意味: "to be employed" },
        葛藤: { 読み方: ['かっとう'], form: '名詞、する動詞、自動詞', 意味: "(feeling of) conflict; reluctance; internal debate" },
        継ぐ: { 読み方: ['つぐ'], form: '五段動詞、他動詞', 意味: "to succeed; inherit; takeover" },
        説得: { 読み方: ['せっとく'], form: '名詞、する動詞、他動詞', 意味: "to persuade" },
        身の上話: { 読み方: ['みのうえばなし'], form: '表現、名詞', 意味: "personal narrative; life story" },
        迫る: { 読み方: ['せまる'], form: '五段動詞、自動詞', 意味: "to press (someone for something); urge" },
        苦痛: { 読み方: ['くつう'], form: 'な形容詞、の形容詞', 意味: "pain; agony" },
        不審がる: { 読み方: ['ふしんがる'], form: '五段動詞', 意味: "to be suspicious (of something or someone)" },
        苦労: { 読み方: ['くろう'], form: '名詞、する動詞', 意味: "to have a hard time" },
        保育園: { 読み方: ['ほいくえん'], form: '名詞', 意味: "nursery school; preschool" },
        付き添う: { 読み方: ['つきそう'], form: '五段動詞、自動詞', 意味: "to escort; to accompany" },
        折々: { 読み方: ['おりおり'], form: '副詞', 意味: "from time to time" },
        しんどい: { 読み方: [''], form: 'い形容詞', 意味: "tiring; tough" },
        陳情: { 読み方: ['ちんじょう'], form: '名詞、する動詞、他動詞', 意味: "to petition; to appeal" },
        事務局長: { 読み方: ['じむきょくちょう'], form: '名詞', 意味: "secretary general" },
        望む: { 読み方: ['のぞむ'], form: '五段動詞、他動詞', 意味: "to hope; want" },
        再婚: { 読み方: ['さいこん'], form: '名詞、する動詞、自動詞', 意味: "to get remarried" },
        戸籍: { 読み方: ['こせき'], form: '名詞', 意味: "family register" },
        戸籍上: { 読み方: ['こせきじょう'], form: '名詞', 意味: "on the family register, offically (legally)" },
        名乗る: { 読み方: ['なのる'], form: '五段動詞、自動詞、他動詞', 意味: "to call oneself" },
        回る: { 読み方: ['まわる'], form: '五段動詞、自動詞', 意味: "to visit several places" },
        採択する: { 読み方: ['採択'], form: '名詞、する動詞、他動詞', 意味: "to adopt (a legislative bill; proposal)" },
        事実婚: { 読み方: ['じじつこん'], form: '名詞', 意味: "common-law marriage; de facto marriage" },
        行政書士: { 読み方: ['ぎょうせいしょし'], form: '名詞', 意味: "certified administrative procedures legal specialist" },
        ペーパー離婚: { 読み方: ['ペーパーりこん'], form: '名詞', 意味: "state of a couple who continue to live together like a married couple even after having legally divorced" },
        取り寄せる: { 読み方: ['とりよせる'], form: '一段動詞、他動詞', 意味: "to order" },
        強制: { 読み方: ['きょうせい'], form: '名詞、する動詞、他動詞', 意味: "enforcement; compulsion" },
        相続: { 読み方: ['そうぞく'], form: '名詞、する動詞、他動詞', 意味: "inheritance; succession" },
        尽きる: { 読み方: ['つきる'], form: '一段動詞、自動詞', 意味: "to be run out; to be used up" },
        ヤジが飛ぶ: { 読み方: ['ヤジがとぶ'], form: '表現', 意味: "[someone] jeers（ヤジを飛ばす：to jeer）" },
        //: { 読み方: [''], form: '', 意味: "" },
    },
    kaku: {
        // Unit 1_1
        かのう: { 読み方: ['可能'], form: 'な形容詞、名詞', 意味: "possible; potential; feasible" },
        よごれる: { 読み方: ['汚れる'], form: '一段動詞、自動詞', 意味: "to get dirty; to become dirty" },
        ひょうめん: { 読み方: ['表面'], form: '名詞、の形容詞', 意味: "surface; exterior; outside; apperances" },
        いぜん: { 読み方: ['以前'], form: '名詞、副詞', 意味: "ago; since; before; previous" },
        おそれ: { 読み方: ['恐れ'], form: '名詞', 意味: "fear; horror; anxiety; concern" },
        もちさる: { 読み方: ['持ち去る'], form: '五段動詞', 意味: "to take away; to carry away" },
        もちぬし: { 読み方: ['持ち主'], form: '名詞', 意味: "owner" },
        うらがわ: { 読み方: ['裏側'], form: '名詞、の形容詞', 意味: "the reverse; the other side" },
        きにいる: { 読み方: ['気に入る'], form: '表現； 五段動詞', 意味: "to like; to take a liking to; to suit one's fancy" },
        こす: { 読み方: ['越す'], form: '五段動詞、尊敬語', 意味: "to go; to come" },
        じじつ: { 読み方: ['事実'], form: '副詞、名詞', 意味: "fact; truth; reality" },

        // Unit 1_2
        こえる: { 読み方: ['越える'], form: '一段動詞、他動詞', 意味: "to surpass; to cross over" },
        どうろ: { 読み方: ['道路'], form: '名詞', 意味: "road; highway" },
        まがる: { 読み方: ['曲がる'], form: '五段動詞、自動詞', 意味: "to turn; to bend; to curve" },
        たに: { 読み方: ['谷'], form: '名詞', 意味: "valley" },
        てんらく: { 読み方: ['転落'], form: '名詞、する動詞、自動詞', 意味: "fall; tumble; plunge" },
        かいかん: { 読み方: ['快感'], form: '名詞', 意味: "pleasant feeling; pleasant sensation; pleasure" },
        はっけん: { 読み方: ['発見'], form: '名詞、する動詞、他動詞', 意味: "discovery; detection; finding" },
        あぶない: { 読み方: ['危ない'], form: 'い形容詞', 意味: "dangerous; perilous; risky; hazardous" },
        いのちしらず: { 読み方: ['命知らず'], form: '名詞、の形容詞、な形容詞', 意味: "recklessness; daredevil; rashness" },
        あたま: { 読み方: ['頭'], form: '名詞', 意味: "head; brains; intellect" },
        そうぞう: { 読み方: ['想像'], form: '名詞、する動詞、他動詞', 意味: "imagination; supposition" },
        

        // Unit 2_1
        ちゅうしゃじょう: { 読み方: ['駐車場'], form: '名詞', 意味: "parking lot" },
        ちゅうねん: { 読み方: ['中年'], form: '名詞、の形容詞', 意味: "middle-age" },
        ひやけ: { 読み方: ['日焼け'], form: '名詞、する動詞、自動詞', 意味: "sunburn; suntan" },
        かんそ: { 読み方: ['簡素'], form: 'な形容詞、名詞', 意味: "modest; simple; plain" },
        いふく: { 読み方: ['衣服'], form: '名詞', 意味: "clothes" },
        かんする: { 読み方: ['（〜に）関する'], form: 'するどうし', 意味: "to concern; to be related" },
        しみん: { 読み方: ['市民'], form: '名詞', 意味: "citizen; townsfolk" },
        みわけ: { 読み方: ['見分け'], form: '名詞', 意味: "distinction" },
        きんがく: { 読み方: ['金額'], form: '名詞', 意味: "amount of money; sum of money" },
        げんてい: { 読み方: ['限定'], form: '名詞、する動詞、の形容詞', 意味: "limit; restriction" },
        もとめる: { 読み方: ['求める'], form: '一段動詞、他動詞', 意味: "to want; to wish for; to request" },
        やく: { 読み方: ['焼く'], form: '五段動詞、他動詞', 意味: "to burn; to heat; to grill" }, 
        におい: { 読み方: ['匂い'], form: '名詞', 意味: "scent; aroma" },
        どうじょう: { 読み方: ['同情'], form: '名詞、する動詞、自動詞', 意味: "sympathy; compassion; pity" },
        さつ: { 読み方: ['札'], form: '名詞', 意味: "banknote; bill; paper money" },
        ておくれ: { 読み方: ['手遅れ'], form: '名詞', 意味: "being too late; losing one's final chance" },


        // Unit 2_2
        ていど: { 読み方: ['程度'], form: '名詞、副詞、接尾詞', 意味: "degree; amount" },
        たんに: { 読み方: ['単に'], form: '副詞', 意味: "simply; merely" },
        ぐたいてき: { 読み方: ['具体的'], form: 'な形容詞', 意味: "specific; definite; concrete" },
        じじょう: { 読み方: ['事情'], form: '名詞', 意味: "circumstances; conditions; situation; state of affairs" },
        はんしゃてき: { 読み方: ['反射的'], form: 'な形容詞', 意味: "reflexive; reflecting" },
        こうふく: { 読み方: ['幸福'], form: '名詞、な形容詞', 意味: "happiness; well-being; joy" },
        いのる: { 読み方: ['祈る'], form: '五段動詞、他動詞', 意味: "to pray; to wish" },
        せっす: { 読み方: ['接する／接す'], form: '五段動詞、する動詞、自動詞', 意味: "to treat; to come in contact with" },
        やさしい: { 読み方: ['優しい'], form: 'い形容詞', 意味: "tender; kind; gentle; affectionate; amiable" },
        きょうし: { 読み方: ['教師'], form: '名詞', 意味: "先生" },
        つきささる: { 読み方: ['突き刺さる'], form: '五段動詞、自動詞', 意味: "to stick into; to pierce" },
        いたむ: { 読み方: ['痛む'], form: '五段動詞、自動詞', 意味: "to hurt; to ache; to feel a pain" },
        とうじ: { 読み方: ['当時'], form: '名詞、副詞', 意味: "at that time; in those days" },
        なまいき: { 読み方: ['生意気'], form: 'な形容詞', 意味: "impertinent; audacious; cocky; cheeky" },
        できごと: { 読み方: ['出来事'], form: '名詞', 意味: "incident; affair; happening; event" },
        にっき: { 読み方: ['日記'], form: '名詞', 意味: "diary; journal" },
        はなまる: { 読み方: ['花丸'], form: '名詞', 意味: "encircled flower seal" },
        いき: { 読み方: ['息'], form: '名詞', 意味: "breath; breathing" },
        つまる: { 読み方: ['詰まる'], form: '五段動詞、自動詞', 意味: "to be packed (with); to be blocked; to be clogged" },
        りろんてき: { 読み方: ['理論的'], form: 'な形容詞', 意味: "theoretical" },
        いらい: { 読み方: ['以来'], form: '名詞、副詞', 意味: "since; henceforth" },
        つねに: { 読み方: ['常に'], form: '副詞', 意味: "always; constantly" },
        きほん: { 読み方: ['基本'], form: '名詞、の形容詞', 意味: "basics; fundamentals; basis; foundation" },

        // Unit 3_1
        やくそく: { 読み方: ['約束'], form: '名詞、する動詞', 意味: "promise; contract" },
        ころ: { 読み方: ['頃'], form: '名詞、副詞、接尾辞', 意味: "(approximate) time; around; about; toward; time of year" },
        こいびと: { 読み方: ['恋人'], form: '名詞', 意味: "lover; sweetheart; significant other" },
        わかれる: { 読み方: ['別れる'], form: '一段動詞、自動詞', 意味: "to part; to part from; to break up" },
        うんめい: { 読み方: ['運命'], form: '名詞、の形容詞', 意味: "destiny; fate" },
        いっしょう: { 読み方: ['一生'], form: '名詞、の形容詞、副詞', 意味: "whole life; a lifetime; (the only, the greatest, etc.) of one's life" },
        ちょくご: { 読み方: ['直後'], form: '名詞、副詞', 意味: "immediately folllowing" },
        とつぜん: { 読み方: ['突然'], form: '名詞、な形容詞、副詞', 意味: "abrupt; sudden; unexpected" },

        // Unit 3_2
        じしん: { 読み方: ['自信'], form: '名詞、する動詞', 意味: "self-confidence; confidence (in oneself)" },
        じつぶつ: { 読み方: ['実物'], form: '名詞', 意味: "real thing; original" },
        はつばい: { 読み方: ['発売'], form: '名詞、する動詞、他動詞', 意味: "sale; offering for sale; release (for sale)" },
        ながれ: { 読み方: ['流れ'], form: '名詞', 意味: "flow (of a fluid, gas, people, things; passage (of time); stream; current; course of events" },
        げんち: { 読み方: ['現地'], form: '名詞', 意味: "actual place; actual location" },
        かち: { 読み方: ['価値'], form: '名詞', 意味: "value; worth; merit" },
        がめん: { 読み方: ['画面'], form: '名詞', 意味: "screen (of a TV, computer, etc.)" },
        りよう: { 読み方: ['利用'], form: '名詞、する動詞、他動詞', 意味: "use; utilization" },
        きょだい: { 読み方: ['巨大'], form: 'な形容詞、名詞', 意味: "huge; gigantic; enormous" },
        ひっし: { 読み方: ['必死'], form: 'な形容詞、の形容詞', 意味: "frantic; desparate" },
        さいど: { 読み方: ['再度'], form: '副詞、名詞', 意味: "a second time; again; once more; twice" },



        // : { 読み方: [''], form: '', 意味: "" },


    },

    yomerebaii: {
        // Unit 1_1
        珍しい: { 読み方: ['めずらしい'], form: 'い形容詞', 意味: "unusual; rare; new" },
        洗濯: { 読み方: ['せんたく'], form: '名詞、する動詞', 意味: "washing; laundry" },
        電源コード: { 読み方: ['でんげんコード'], form: '名詞', 意味: "power cord" },
        延びる: { 読み方: ['のびる'], form: '一段動詞、自動詞', 意味: "to stretch; to extend; to lengthen; to grow; to be prolonged (meeting; lifespan)" },
        泥: { 読み方: ['どろ'], form: '名詞', 意味: "mud" },
        側面: { 読み方: ['そくめん'], form: '名詞', 意味: "side; flank" },
        明記: { 読み方: ['めいき'], form: '名詞、する動詞、他動詞', 意味: "to make clear; specification" },
        塩: { 読み方: ['しお'], form: '名詞', 意味: "salt" },
        製: { 読み方: ['〜せい'], form: '接尾詞', 意味: "-made; make" },
        振る: { 読み方: ['ふる'], form: '五段動詞、他動詞', 意味: "to wave; to shake" },
        奥: { 読み方: ['おく'], form: '名詞', 意味: "(further in) back" },
        事態: { 読み方: ['じたい'], form: '名詞', 意味: "state (of affairs/things); circumstances" },
        比較的: { 読み方: ['ひかくてき'], form: '副詞', 意味: "comparatively; relatively" },

        // Unit 1_2
        峠: { 読み方: ['とうげ'], form: '名詞', 意味: "mountain peak" },
        険しい: { 読み方: ['けわしい'], form: 'い形容詞', 意味: "steep; grim" },
        誤る: { 読み方: ['あやまる'], form: '五段動詞、他動詞', 意味: "to make a mistake (in); to commit an error; to be wrong" },
        恐怖: { 読み方: ['きょうふ'], form: '名詞、する動詞', 意味: "fear; dread; dismay; terror; horror" },
        標識: { 読み方: ['ひょうしき'], form: '名詞', 意味: "sign; mark; flag" },

        // Unit 2_1
        滞在: { 読み方: ['たいざい'], form: '名詞、する動詞、自動詞', 意味: "stay" },
        髪: { 読み方: ['かみ'], form: '名詞', 意味: "hair (on the head)" },
        服装: { 読み方: ['ふくそう'], form: '名詞', 意味: "attire; garment" },
        お腹: { 読み方: ['おなか'], form: '名詞', 意味: "belly; stomach" },
        街角: { 読み方: ['まちかど'], form: '名詞', 意味: "street corner" },
        小銭: { 読み方: ['こぜに'], form: '名詞', 意味: "small change; coins" },
        援助: { 読み方: ['えんじょ'], form: '名詞、する動詞、他動詞', 意味: "assistance; aid; support" },
        漂う: { 読み方: ['ただよう'], form: '五段動詞、自動詞', 意味: "to drift; to float; to waft (e.g. a scent)" },
        訴える: { 読み方: ['うったえる'], form: '一段動詞、他動詞', 意味: "to bring to (someone's attention); to appeal to (reason, emotions, etc.); to play on (one's sympathies); to sue" },
        企画力: { 読み方: ['きかくりょく'], form: '名詞', 意味: "planning ability" },
        財布: { 読み方: ['さいふ'], form: '名詞', 意味: "wallet; handbag; purse" },
        浮かぶ: { 読み方: ['うかぶ'], form: '五段動詞', 意味: "to float; to be suspended" },

        // Unit 2_2
        教訓: { 読み方: ['きょうくん'], form: '名詞', 意味: "moral; lesson; teachings" },
        隅: { 読み方: ['すみ'], form: '名詞', 意味: "corner; nook" },
        胸: { 読み方: ['むね'], form: '名詞', 意味: "chest" },
        巣: { 読み方: ['す'], form: '名詞', 意味: "nest; breeding place; hive; (spider's) web; den" },
        提出: { 読み方: ['ていしゅつ'], form: '名詞、する動詞、他動詞', 意味: "turning in; submission (of an application, report, etc.)" },
        一連: { 読み方: ['いちれん'], form: '名詞、の形容詞', 意味: "series" },
        意気揚々: { 読み方: ['いきようよう'], form: 'たる形容詞、と副詞', 意味: "triumphant; in high and proud spirits" },

        //Unit 3_1
        我々: { 読み方: ['われわれ'], form: '代名詞', 意味: "we" },
        仲: { 読み方: ['なか'], form: '名詞', 意味: "relation; relationship" },
        酒場: { 読み方: ['さかば'], form: '名詞', 意味: "bar; pub; tavern" },
        壊す: { 読み方: ['こわす'], form: '五段動詞、他動詞', 意味: "to break; to destroy" },
        忠告: { 読み方: ['ちゅうこく'], form: '名詞、する動詞、の形容詞、他動詞', 意味: "advice; warning" },
        永遠: { 読み方: ['えいえん'], form: '名詞、の形容詞、な形容詞', 意味: "eternity" },
        結局: { 読み方: ['けっきょく'], form: '副詞、名詞、の形容詞', 意味: "after all; in the end; ultimately; conclusion; end" },
        存在: { 読み方: ['そんざい'], form: '名詞、する動詞、の形容詞、自動詞', 意味: "existence; being" },
        空白: { 読み方: ['くうはく'], form: '名詞、な形容詞、の形容詞', 意味: "vacuum; blank; void; blank space (in documents)" },
        周辺: { 読み方: ['しゅうへん'], form: '名詞', 意味: "circumference; outskirts; in the area of; in the vicinity of" },
        前触れ: { 読み方: ['まえぶれ'], form: '名詞、する動詞、自動詞', 意味: "advance warning; previous notice; prior announcement" },
        出張: { 読み方: ['しゅっちょう'], form: '名詞、する動詞、自動詞', 意味: "business trip" },
        札幌: { 読み方: ['さっぽろ'], form: '名詞', 意味: "Sapporo (city in Hokkaido)" },

        // Unit 3_2
        昆虫: { 読み方: ['こんちゅう'], form: '名詞、の形容詞', 意味: "insect; bug" },
        箱: { 読み方: ['はこ／ーばこ'], form: '名詞', 意味: "box; case; packge" },
        採集: { 読み方: ['さいしゅう'], form: '名詞、する動詞、他動詞', 意味: "collecting; gathering" },
        満足: { 読み方: ['まんぞく'], form: '名詞、な形容詞、する動詞', 意味: "satisfaction; contentment; sufficient; satisfactory; enough; adequate" },
        同級生: { 読み方: ['どうきゅうせい'], form: '名詞', 意味: "classmate" },
        本格的: { 読み方: ['ほんかくてき'], form: 'な形容詞', 意味: "genuine; real; authentic; full-scale; proper; full-fledged" },
        悪気: { 読み方: ['わるぎ'], form: '名詞', 意味: "ill will; malice; evil intent" },
        文句: { 読み方: ['もんく'], form: '名詞', 意味: "complaint; objection; grumbling" },
        指: { 読み方: ['ゆび'], form: '名詞', 意味: "finger; toe" },
        冗談: { 読み方: ['じょうだん'], form: '名詞', 意味: "joke; jest; funny story" },
        動作: { 読み方: ['どうさ'], form: '名詞、する動詞、自動詞', 意味: "movement (of the body); motion; behavior; operation (of a machine, software, etc.)" },
        確認: { 読み方: ['かくにん'], form: '名詞、する動詞、他動詞', 意味: "confirmation; verification; validation" },
        作業: { 読み方: ['さぎょう'], form: '名詞、する動詞', 意味: "work; operatin; manufacturing; fatigue duty" },
        冷蔵庫: { 読み方: ['れいぞうこ'], form: '名詞', 意味: "fridge" },
        警察: { 読み方: ['けいさつ'], form: '名詞', 意味: "police" },
        真剣: { 読み方: ['しんけん'], form: 'な形容詞', 意味: "serious; earnest" },
        飛び出す: { 読み方: ['とびだす'], form: '五段動詞、自動詞', 意味: "to jump out; to rush out; to fly out" },
        商店街: { 読み方: ['しょうてんがい'], form: '名詞', 意味: "shopping district; shopping street; downtown" },

        // Unit 4_1
        記者: { 読み方: ['きしゃ'], form: '名詞', 意味: "reporter; journalist"  },
        名字: { 読み方: ['みょうじ'], form: '名詞', 意味: "last name; family name; surname"  },
        用紙: { 読み方: ['ようし'], form: '名詞', 意味: "blank forms; sheets of paper"  },
        違和感: { 読み方: ['いわかん'], form: '名詞', 意味: "uncomfortable feeling; feeling out of place"  },
        運転免許証: { 読み方: ['うんてんめんきょしょう'], form: '名詞', 意味: "driver's license"  },
        窓口: { 読み方: ['まどぐち'], form: '名詞', 意味: "counter; window"  },
        身分証: { 読み方: ['みぶんしょう'], form: '名詞', 意味: "identification papers; ID"  },
        会員証: { 読み方: ['かいいんしょう'], form: '名詞', 意味: "membership card; membership certificate"  },
        混乱: { 読み方: ['こんらん'], form: '名詞、する動詞、自動詞', 意味: "confusion; chaos"  },
        報告: { 読み方: ['ほうこく'], form: '名詞、する動詞、他動詞', 意味: "report; information"  },
        制度: { 読み方: ['せいど'], form: '名詞、の形容詞', 意味: "system; institution"  },
        調査: { 読み方: ['ちょうさ'], form: '名詞、する動詞、他動詞', 意味: "investigation; survey"  },
        姉妹: { 読み方: ['しまい'], form: '名詞', 意味: "sisters"  },
        求める: { 読み方: ['もとめる'], form: '一段動詞、他動詞', 意味: "to want; to wish for; to request"  },
        末: { 読み方: ['〜のすえ'], form: '副詞、名詞', 意味: "(finally/at last) after~; at the end of~"  },
        加わる: { 読み方: ['くわわる'], form: '五段動詞、自動詞', 意味: "to be added; to join in (group of friends); to increase (e.g. heat); to gain in (e.g. influence)"  },
        議会: { 読み方: ['ぎかい'], form: '名詞', 意味: "congress; parliament; diet"  },
        離婚: { 読み方: ['りこん'], form: '名詞、する動詞、自動詞', 意味: "divorce"  },
        都合: { 読み方: ['〜のつごうで'], form: '副詞、名詞', 意味: "circumstances; for reasons of~"  },
        議員: { 読み方: ['ぎいん'], form: '名詞', 意味: "member of the Diet; member of parliament"  },
        同意: { 読み方: ['どうい'], form: '名詞、する動詞、自動詞', 意味: "agreement; consent; same opinion"  },
        死亡: { 読み方: ['しぼう'], form: '名詞、する動詞、自動詞', 意味: "death; dying"  },
        国会: { 読み方: ['こっかい'], form: '名詞', 意味: "National Diet; legislative assembly of Japan"  },



        // : { 読み方: [''], form: '', 意味: ""  },
    }
}
export default kanji;   