const kanji = {
    tango: {
        // Unit 1_1
        面する: { 読み方: ['（〜に）めんする'], form: 'する動詞', 意味: "to face~" },
        今どき: { 読み方: ['いまどき'], form: '名詞、副詞', 意味: "nowadays" },
        珍しい: { 読み方: ['めずらしい'], form: 'イ形容詞', 意味: "unusual; rare; curious" },
        壁: { 読み方: ['かべ'], form: '名詞', 意味: "wall" },
        立て掛ける: { 読み方: ['（〜に）たてかける'], form: '他動詞', 意味: "ot lean (something against~)" },
        無造作: { 読み方: ['むぞうさ'], form: 'ナ形容詞', 意味: "casual; careless" },
        張り紙: { 読み方: ['はりがみ'], form: '名詞', 意味: "（＝貼り紙）a sign, poster" },
        可能: { 読み方: ['かのう'], form: 'ナ形容詞、名詞', 意味: "possible; potential; feasible" },
        断り書き: { 読み方: ['ことわりガキ'], form: '名詞', 意味: "disclaimer" },
        込める: { 読み方: ['こめる'], form: '一段動詞、他動詞', 意味: "to infuse; load; put" },
        電源コード: { 読み方: ['でんげんコード'], form: '名詞', 意味: "power cord" },
        延びる: { 読み方: ['のびる'], form: '一段動詞、自動詞', 意味: "to extend;" },
        切れる: { 読み方: ['（スイッチが）きれる'], form: '一段動詞、自動詞', 意味: "to be cut; to stop working; to go dead; " },
        ところどころ: { 読み方: [''], form: '副詞、名詞', 意味: "here and there; in places" },
        サビつく: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to rust; to beocme rusty" },
        泥: { 読み方: ['どろ'], form: '名詞', 意味: "mud" },
        泥がはねる: { 読み方: ['どろがはねる'], form: '表現、一段動詞、他動詞', 意味: "to splash with mud" },
        側面: { 読み方: ['そくめん'], form: '名詞', 意味: "side" },
        汚れる: { 読み方: ['よごれる'], form: '一段動詞、自動詞', 意味: "to get dirty; to become dirty" },
        表面: { 読み方: ['ひょうめん'], form: '名詞', 意味: "surface; exterior" },
        プリント: { 読み方: [''], form: '名詞', 意味: "printed images/texts" },
        以前: { 読み方: ['いぜん'], form: '名詞、副詞', 意味: "ago; since; before; previous" },
        恐れがある: { 読み方: ['おそれがある'], form: '表現', 意味: "there is a danger (possibility) that..." },
        明記: { 読み方: ['めいき'], form: '名詞、スル動詞、他動詞', 意味: "clear writing; specification" },
        解釈: { 読み方: ['かいしゃく'], form: '名詞、スル動詞、他動詞', 意味: "interpretation; to interpret (the meaning);" },
        持ち去る: { 読み方: ['もちさる'], form: '五段動詞', 意味: "to take away; to carry away" },
        やつ: { 読み方: [''], form: '名詞、代名詞', 意味: "guy; he/him; [vulgar version of] a \"person\" or a \"thing\"" },
        一度や二度ではない: { 読み方: ['いちどやにどではない'], form: '表現', 意味: "not just once or twice = many times" },
        持ち主: { 読み方: ['もちぬし'], form: '名詞', 意味: "owner" },
        行為: { 読み方: ['こうい'], form: '名詞', 意味: "action; act; deed; conduct" },
        裏側: { 読み方: ['うらがわ'], form: '名詞', 意味: "the reverse side; other side" },
        廊下: { 読み方: ['ろうか'], form: '名詞', 意味: "hallway; corridor" },
        ほっとく: { 読み方: [''], form: '表現', 意味: "＝（人を）ほうっておくto leave someone alone" },
        ある種: { 読み方: ['あるしゅの'], form: '名詞、ノ形容詞', 意味: "a sort of~; certain; some kind of" },
        気に入る: { 読み方: ['きにいる'], form: '表現、五段動詞', 意味: "to like; come into someone's favor" },
        越す: { 読み方: ['こす'], form: '五段動詞、尊敬語', 意味: "to go; to come" },
        瓶: { 読み方: ['びん'], form: '名詞', 意味: "bottle" },
        容器: { 読み方: ['ようき'], form: '名詞', 意味: "container; vessel; packaging" },
        塩: { 読み方: ['しお'], form: '名詞', 意味: "salt" },
        見かける: { 読み方: ['みかける'], form: '一段動詞、他動詞', 意味: "to see; come across; to catch sight of; to (happen to) see" },
        透明: { 読み方: ['とうめい'], form: 'ナ形容詞', 意味: "transparent; clear" },
        蓋: { 読み方: ['ふた'], form: '名詞', 意味: "cover; lid; cap" },
        穴: { 読み方: ['あな'], form: '名詞', 意味: "hole" },
        振る: { 読み方: ['ふる'], form: '五段動詞、他動詞', 意味: "to wave; to shake" },
        山盛り: { 読み方: ['やまもり'], form: '名詞、ノ形容詞', 意味: "heap" },
        ロビー: { 読み方: [''], form: '名詞', 意味: "lobby" },
        奥: { 読み方: ['おく'], form: '名詞', 意味: "(further in) back" },
        便座: { 読み方: ['べんざ'], form: '名詞', 意味: "toilet seat" },
        目撃: { 読み方: ['もくげき'], form: '名詞、スル動詞、他動詞', 意味: "witnessing; observing; sighting" },
        事実: { 読み方: ['じじつ'], form: '副詞、名詞', 意味: "fact; truth; reality" },
        足跡: { 読み方: ['あしあと'], form: '名詞', 意味: "footprint" },
        後を絶たない: { 読み方: ['あしをたたない'], form: '表現、イ形容詞', 意味: "never ceasing; never ending; endless" },
        事態: { 読み方: ['じたい'], form: '名詞', 意味: "state (of affairs/things); circumstances" },
        特有: { 読み方: ['とくゆう'], form: 'の形容詞、な形容詞', 意味: "characteristic (of); peculiar (of)" },
        比較的: { 読み方: ['ひかくてき'], form: '副詞', 意味: "comparatively; relatively" },
        謎: { 読み方: ['なぞ'], form: '名詞', 意味: "mystery; riddle" },
        板壁: { 読み方: ['いたかべ'], form: '名詞', 意味: "wooden wall" },
        丹念: { 読み方: ['たんねん'], form: 'な形容詞、名詞', 意味: "careful; patient; meticulous" },
        色あせる: { 読み方: ['いろあせる'], form: '一段動詞、自動詞', 意味: "to fade in color" },
        潜む: { 読み方: ['ひそむ'], form: '五段動詞、自動詞', 意味: "to lurk; to be hidden; to be concealed; to be dormant" },
        無法地帯: { 読み方: ['むほうちたい'], form: '名詞', 意味: "lawless area; lawless district" },
        醤油差し: { 読み方: ['しょうゆさし'], form: '名詞', 意味: "soy sauce bottle" },
        爪楊枝: { 読み方: ['つまようじ'], form: '名詞', 意味: "toothpick" },
        ガラス製: { 読み方: ['ガラスせい'], form: 'の形容詞', 意味: "(made of) glass" },
        塞ぐ: { 読み方: ['ふさぐ'], form: '五段動詞、他動詞', 意味: "to block; cover; clog up" },
        金属製: { 読み方: ['きんぞくせい'], form: '名詞、の形容詞', 意味: "(made from) metal; metallic" },
        常人: { 読み方: ['じょうじん'], form: '名詞', 意味: "ordinary person" },

        // Unit 1_2
        峠: { 読み方: ['とうげ'], form: '名詞', 意味: "mountain peak" },
        越える: { 読み方: ['こえる'], form: '一段動詞、他動詞', 意味: "to surpass; to cross over" },
        峠を越える: { 読み方: ['とうげをこえる'], form: '表現、一段動詞、他動詞', 意味: "to pass the peak; to be over the worse" },
        険しい: { 読み方: ['けわしい'], form: 'い形容詞', 意味: "steep; grim" },
        曲がりくねる: { 読み方: ['まがりくねる'], form: '五段動詞、自動詞', 意味: "to turn and twist; to bend many times; to zigzag" },
        谷: { 読み方: ['たに'], form: '名詞', 意味: "valley" },
        ハンドル: { 読み方: [''], form: '名詞', 意味: "steering wheel" },
        操作: { 読み方: ['そうさ'], form: '名詞、する動詞、他動詞', 意味: "operation; handling" },
        誤る: { 読み方: ['あやまる'], form: '五段動詞、他動詞', 意味: "to make a mistake (in); to commit an error; to be wrong" },
        一瞬にして: { 読み方: ['いっしゅんにして'], form: '表現、副詞', 意味: "in an instant; in a moment; instantaneously" },
        転落: { 読み方: ['てんらく'], form: '名詞、する動詞、自動詞', 意味: "fall; tumble; plunge" },
        ジェットコースター: { 読み方: [''], form: '名詞', 意味: "roller coaster" },
        恐怖: { 読み方: ['きょうふ'], form: '名詞、する動詞', 意味: "fear; dread; dismay; terror; horror" },
        快感: { 読み方: ['かいかん'], form: '名詞', 意味: "pleasant feeling; pleasant sensation; pleasure" },
        はし: { 読み方: ['（〜の）はし'], form: '名詞', 意味: "end; tip; edge; margin" },
        標識: { 読み方: ['ひょうしき'], form: '名詞', 意味: "sign; mark; flag" },
        発見: { 読み方: ['はっけん'], form: '名詞、する動詞、他動詞', 意味: "discovery; detection; finding" },
        鮮やか: { 読み方: ['あざやか'], form: 'な形容詞', 意味: "vivid; bright; vibrant; skillful; brilliant" },
        命知らず: { 読み方: ['いのちしらず'], form: '名詞、の形容詞、な形容詞', 意味: "recklessness; daredevil; rashness" },
        わき: { 読み方: ['（〜の）わき'], form: '名詞', 意味: "side; beside" },
        プレート: { 読み方: [''], form: '名詞', 意味: "plate" },
        プラスチック: { 読み方: [''], form: '名詞', 意味: "plastic" },
        想像: { 読み方: ['そうぞう'], form: '名詞、する動詞、他動詞', 意味: "imagination; supposition" },
        際: { 読み方: ['（〜の）きわ／ぎわ'], form: '名詞、接尾辞', 意味: "edge; verge" },
        敷設: { 読み方: ['ふせつ'], form: '名詞、する動詞、他動詞', 意味: "to lay (a railroad, pipes, naval mines, etc.)" },
        同居: { 読み方: ['どうきょ'], form: '名詞、する動詞、自動詞', 意味: "living together; coexistence" },
        端的: { 読み方: ['たんてき'], form: 'な形容詞', 意味: "straightfoward; concise; plain; direct; frank" },
        塗料: { 読み方: ['とりょう'], form: '名詞', 意味: "paint" },



        // Unit 2_1
        法則: { 読み方: ['ほうそく'], form: '名詞', 意味: "rule; law" },
        仲間: { 読み方: ['なかま'], form: '名詞', 意味: "companion; friend" },
        以外: { 読み方: ['いがい'], form: '名詞、福祉', 意味: "except; other than; besides" },
        風景: { 読み方: ['ふうけい'], form: '名詞', 意味: "scenery" },
        社会学者: { 読み方: ['しゃかいがくしゃ'], form: '名詞', 意味: "sociologist" },
        公共: { 読み方: ['こうきょう'], form: '名詞', 意味: "public (facilities); communal" },
        電柱: { 読み方: ['でんちゅう'], form: '名詞', 意味: "utility pole; telephone pole" },
        映る: { 読み方: ['うつる'], form: '五段動詞、自動詞', 意味: "to be reflected; to be displayed (on a screen); to be projected" },
        きわめて: { 読み方: [''], form: '副詞', 意味: "extremeley" },
        信頼性: { 読み方: ['しんらいせい'], form: '名詞', 意味: "credibility; reliability" },
        通じる: { 読み方: ['つうじる'], form: '一段動詞、自動詞', 意味: "to apply; to lead; to get across" },
        満員電車: { 読み方: ['まんいんでんしゃ'], form: '名詞', 意味: "full-train" },
        家具: { 読み方: ['かぐ'], form: '名詞', 意味: "furniture" },
        植木鉢: { 読み方: ['うえきばち'], form: '名詞', 意味: "potted plant" },
        車両: { 読み方: ['しゃりょう'], form: '名詞', 意味: "wheeled vehicle" },
        感覚: { 読み方: ['かんかく'], form: '名詞、スル動詞', 意味: "sense; feeling; sensation" },
        平気: { 読み方: ['へいき'], form: 'ナ形容詞', 意味: "ok; all right" },
        化粧: { 読み方: ['けしょう'], form: '名詞、スル動詞', 意味: "make-up" },
        弁当: { 読み方: ['べんとう'], form: '名詞', 意味: "boxed lunch" },
        机: { 読み方: ['つくえ'], form: '名詞', 意味: "desk" },
        傍若無人: { 読み方: ['ぼうじゃくぶじん'], form: '名詞、ナ形容詞、ノ形容詞', 意味: "insolence; outrageous; arrogant" },
        謎: { 読み方: ['なぞ'], form: '名詞', 意味: "mystery" },
        解く: { 読み方: ['とく'], form: '五段動詞、他動詞', 意味: "to solve" },
        解ける: { 読み方: ['とける'], form: '一段動詞、自動詞', 意味: "to be solved" },
        勝手: { 読み方: ['かって'], form: 'ナ形容詞、名詞', 意味: "selfishness; one's own convenience" },
        全体: { 読み方: ['ぜんたい'], form: '名詞、副詞', 意味: "whole; entire; general" },
        全員: { 読み方: ['ぜんいん'], form: '名詞、副詞', 意味: "all members; everybody" },
        共有: { 読み方: ['きょうゆう'], form: '名詞、スル動詞', 意味: "sharing (e.g. a viewpoint), sharing (files)" },
        摩擦: { 読み方: ['まさつ'], form: '名詞、スル動詞', 意味: "friction; conflict" },
        迷惑: { 読み方: ['めいわく'], form: '名詞、ナ形容詞', 意味: "trouble; bother; annoyance; nuisance; inconvenience" },
        被害: { 読み方: ['ひがい'], form: '名詞', 意味: "damage; injury; harm" },
        及ぶ: { 読み方: ['およぶ'], form: '五段動詞、自動詞', 意味: "to reach" },
        限り: { 読み方: ['～かぎり'], form: '動詞＋限り', 意味: "as long as~" },
        みっともない: { 読み方: [''], form: 'イ形容詞', 意味: "disgraceful; embarassing; ugly" },
        不愉快: { 読み方: ['ふゆかい'], form: 'ナ形容詞', 意味: "unpleasant" },
        //: { 読み方: [''], form: '', 意味: "" },

        // Unit 2_2
        標準: { 読み方: ['ひょうじゅん'], form: '名詞', 意味: "standard; norm" },
        かなり: { 読み方: [''], form: '副詞', 意味: "considerably; fairly; quite" },
        高度: { 読み方: ['こうど'], form: 'ナ形容詞', 意味: "high degree; high-grade; advanced; sophisticated" },
        要する: { 読み方: ['ようする'], form: 'スル動詞、他動詞', 意味: "to need; to demand; to require" },
        暴力的: { 読み方: ['ぼうりょくてき'], form: 'ナ形容詞', 意味: "violent" },
        酔っ払う: { 読み方: ['よっぱらう'], form: '五段動詞、自動詞', 意味: "to get drunk" },
        理性: { 読み方: ['りせい'], form: '名詞', 意味: "(a sense of) reasoning; reason" },
        意志: { 読み方: ['いし'], form: '名詞', 意味: "will; intention; intent; determination" },
        弱まる: { 読み方: ['よわまる'], form: '五段動詞、自動詞', 意味: "to abate; to weaken; to be emaciated" },
        ぶつかる: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to strike against; to collide with; to bump into" },
        駅員: { 読み方: ['えきいん'], form: '名詞', 意味: "(train) station attendant; station employee/staff" },
        なぐりかかる: { 読み方: [''], form: '五段動詞、自動詞', 意味: "to throw a punch at; to swing at" },
        寛大: { 読み方: ['かんだい'], form: 'ナ形容詞、名詞', 意味: "tolerant; generous; lenient" },
        無視: { 読み方: ['むし'], form: '名詞、スル動詞', 意味: "ignoring; disregarding" },
        意外: { 読み方: ['いがい'], form: 'ナ形容詞', 意味: "unexpected; surprising" },
        周囲: { 読み方: ['しゅうい'], form: '名詞', 意味: "surroundings" },
        家庭: { 読み方: ['かてい'], form: '名詞', 意味: "home; family; household" },
        好き勝手: { 読み方: ['すきかって'], form: 'ナ形容詞', 意味: "doing whatever one pleases" },
        着替える: { 読み方: ['きがえる'], form: '一段動詞', 意味: "to change one's clothes" },
        済ませる: { 読み方: ['すませる'], form: '一段動詞、他動詞', 意味: "to finish; get it done（＝済む）" },
        耐える: { 読み方: ['たえる'], form: '一段動詞、自動詞、他動詞', 意味: "to bear; to stand; to endure; to put up with" },
        キレる: { 読み方: [''], form: '一段動詞、自動詞', 意味: "to get angry; lose one's temper" },
        続出: { 読み方: ['ぞくしゅつ'], form: '名詞、スル動詞', 意味: "appearing one after another" },
        実行: { 読み方: ['じっこう'], form: '名詞、スル動詞', 意味: "execution (e.g. of a plan); carrying out" },
        ある種: { 読み方: ['あるしゅ'], form: '名詞、ノ形容詞', 意味: "certain kind of~; some sort of" },
        言い切る: { 読み方: ['いいきる'], form: '五段動詞、他動詞', 意味: "to say positively; declare; assert" },
        使用: { 読み方: ['しよう'], form: '名詞、スル動詞', 意味: "use; application; utilization" },
        ごく: { 読み方: [''], form: '副詞', 意味: "quite; very" },
        小声: { 読み方: ['こごえ'], form: '名詞、ノ形容詞', 意味: "low voice; whisper" },
        個室: { 読み方: ['こしつ'], form: '名詞', 意味: "private room; single room" },
        保つ: { 読み方: ['たもつ'], form: '五段動詞、他動詞', 意味: "to keep; to preserve; to maintain" },
        光景: { 読み方: ['こうけい'], form: '名詞', 意味: "scene; spectacle; sight; view" },
        いっさい: { 読み方: [''], form: '名詞、ノ形容詞', 意味: "all; whole; entirely" },
        逸脱: { 読み方: ['いつだつ'], form: '名詞、スル動詞', 意味: "deviation; departure" },
        静けさ: { 読み方: ['しずけさ'], form: '名詞', 意味: "stillness; silence; calm; serenity" },

        // Unit 3_1
        地球温暖化: { 読み方: ['ちきゅうおんだんか'], form: '名詞', 意味: "global warming" },
        排出: { 読み方: ['はいしゅつ'], form: '名詞、スル動詞', 意味: "emission (e.g. of CO2, etc.)" },
        二酸化炭素: { 読み方: ['にさんかたんそ'], form: '名詞', 意味: "carbon dioxide" },
        水道: { 読み方: ['すいどう'], form: '名詞', 意味: "water supply" },
        暖房: { 読み方: ['だんぼう'], form: '名詞、スル動詞', 意味: "(indoor) heating" },
        冷房: { 読み方: ['れいぼう'], form: '名詞、スル動詞', 意味: "air conditioning; air cooling" },
        利用: { 読み方: ['りよう'], form: '名詞、スル動詞', 意味: "use; utilization" },
        お風呂: { 読み方: ['おふろ'], form: '名詞', 意味: "bath" },
        洗濯: { 読み方: ['せんたく'], form: '名詞、スル動詞', 意味: "washsing; laundry" },
        入浴: { 読み方: ['にゅうよく'], form: '名詞', 意味: "bathing; to bathe; to enter a bath" },
        炊飯器: { 読み方: ['すいはんき'], form: '名詞', 意味: "rice cooker" },
        保温: { 読み方: ['ほおん'], form: '名詞、スル動詞', 意味: "heat-retention; heat insulation" },
        冷蔵庫: { 読み方: ['れいぞうこ'], form: '名詞', 意味: "refrigerator; fridge" },
        詰め込む: { 読み方: ['つめこむ'], form: '五段動詞、他動詞', 意味: "to cram; to stuff; to pack" },
        壁: { 読み方: ['かべ'], form: '名詞', 意味: "wall" },
        適切: { 読み方: ['てきせつ'], form: 'ナ形容詞', 意味: "appropriate; suitable" },
        消す: { 読み方: ['けす'], form: '五段動詞、他動詞', 意味: "to erase; to turn off (power); to switch off" },
        節約: { 読み方: ['せつやく'], form: '名詞、スル動詞', 意味: "economising; saving" },
        削減: { 読み方: ['さくげん'], form: '名詞、スル動詞', 意味: "cut; reduction" },
        環境: { 読み方: ['かんきょう'], form: '名詞', 意味: "environment; circumstance" },
        活動: { 読み方: ['かつどう'], form: '名詞、スル動詞', 意味: "activity (of a person, organization, animal, volcano, etc.)" },
        購入: { 読み方: ['こうにゅう'], form: '名詞、スル動詞', 意味: "purchase; buy" },
        買い物袋: { 読み方: ['かいものぶくろ'], form: '名詞', 意味: "shopping bag" },
        洗剤: { 読み方: ['せんざい'], form: '名詞', 意味: "detergent; cleanser; cleaning agent" },
        中身: { 読み方: ['なかみ'], form: '名詞', 意味: "contents; interior; filling" },
        電球: { 読み方: ['でんきゅう'], form: '名詞', 意味: "light bulb" },
        切れる: { 読み方: ['きれる'], form: '一段動詞、自動詞', 意味: "to wear out; to be burned out" },
        取り替える: { 読み方: ['とりかえる'], form: '一段動詞、他動詞', 意味: "to exchange; to replace" },
        繰り返し: { 読み方: ['くりかえし'], form: '名詞、副詞', 意味: "repetition; repeatedly" },
        瓶: { 読み方: ['びん、ビン'], form: '名詞', 意味: "bottle; jar" },
        製品: { 読み方: ['せいひん'], form: '名詞', 意味: "product; manufactured goods" },
        家電製品: { 読み方: ['かでんせいひん'], form: '名詞', 意味: "consumer electronics; home appliances" },
        心がける: { 読み方: ['こころがける'], form: '一段動詞、他動詞', 意味: "to keep in mind; to bear in mind; to endeavor; to try (to~)" },
        取り組み: { 読み方: ['とりくみ'], form: '名詞', 意味: "effort; approach; initiative" },
        積み重ねる: { 読み方: ['つみかさねる'], form: '一段動詞、他動詞', 意味: "to pile up; to accumulate" },
        一般廃棄物: { 読み方: ['いっぱんはいきぶつ'], form: '名詞', 意味: "domestic waste" },
        給湯: { 読み方: ['きゅうとう'], form: '名詞、スル動詞', 意味: "hot-water supply" },
        厨房: { 読み方: ['ちゅうぼう'], form: '名詞', 意味: "kitchen" },
        動力: { 読み方: ['どうりょく'], form: '名詞', 意味: "motor; power" },
        自家用乗用車: { 読み方: ['じかようじょうようしゃ'], form: '名詞', 意味: "private (passenger) car" },
        残り湯: { 読み方: ['のこりゆ'], form: '名詞', 意味: "leftover bath water" },
        使いまわす: { 読み方: ['つかいまわす'], form: '五段動詞', 意味: "to recycle; to use the same thing for more than one purpose" },
        間隔: { 読み方: ['かんかく'], form: '名詞', 意味: "interval; sapce between two objects" },
        温水洗浄便座: { 読み方: ['おんすいせんじょうべんざ'], form: '名詞', 意味: "bidet toilet seat" },
        炎: { 読み方: ['ほのお'], form: '名詞', 意味: "glame; fire" },
        はみ出す: { 読み方: ['はみだす'], form: '五段動詞、自動詞', 意味: "to stick out; (flame) come out/up (the side of a pot)" },
        なべ底: { 読み方: ['なべぞこ'], form: '名詞', 意味: "the (inner) bottom of a pan" },
        調節: { 読み方: ['ちょうせつ'], form: '名詞、スル動詞', 意味: "adjustment; regulation" },
        設置: { 読み方: ['せっち'], form: '名詞、スル動詞', 意味: "installation (of a machine or equipment)" },
        主電源: { 読み方: ['しゅでんげん'], form: '名詞', 意味: "main power supply" },
        こまめ: { 読み方: [''], form: 'ナ形容詞', 意味: "frequent (e.g. checking); diligent; earnest" },
        こまめに: { 読み方: [''], form: '副詞', 意味: "frequently" },
        待機電力: { 読み方: ['たいきでんりょく'], form: '名詞', 意味: "standby power" },
        設定温度: { 読み方: ['せっていおんど'], form: '名詞', 意味: "preset temperature" },
        宣言: { 読み方: ['せんげん'], form: '名詞、スル動詞', 意味: "declaration" },
        推進: { 読み方: ['すいしん'], form: '名詞、スル動詞', 意味: "promotion; propulsion" },
        環境省: { 読み方: ['かんきょうしょう'], form: '名詞', 意味: "Ministry of the Environment" },
        防止: { 読み方: ['ぼうし'], form: '名詞、スル動詞', 意味: "prevention" },
        原則: { 読み方: ['げんそく'], form: '名詞', 意味: "general rule; principle" },
        包装: { 読み方: ['ほうそう'], form: '名詞、スル動詞', 意味: "package; wrapping" },
        詰め替える: { 読み方: ['つめかえる'], form: '一段動詞、他動詞', 意味: "to repack; to refill" },
        電球型蛍光ランプ: { 読み方: ['でんきゅうがたけいこうランプ'], form: '名詞', 意味: "compact fluorescent lamp (CFL)" },
        エネルギー効率: { 読み方: ['エネルギーこうりつ'], form: '名詞', 意味: "energy efficiency" },
        燃費: { 読み方: ['ねんぴ'], form: '名詞', 意味: "fuel consumption; gas mileage" },
        鉄道: { 読み方: ['てつどう'], form: '名詞', 意味: "railroad; rail" },
        配慮: { 読み方: ['はいりょ'], form: '名詞、スル動詞', 意味: "attention; consideration" },
        参考: { 読み方: ['さんこう'], form: '名詞', 意味: "reference" },

        
        //: { 読み方: [''], form: '', 意味: "" },
    },
    kaku: {
        // Unit 1_1
        かのう: { 読み方: ['可能'], form: 'な形容詞、名詞', 意味: "possible; potential; feasible" },
        よごれる: { 読み方: ['汚れる'], form: '一段動詞、自動詞', 意味: "to get dirty; to become dirty" },
        ひょうめん: { 読み方: ['表面'], form: '名詞、の形容詞', 意味: "surface; exterior; outside; apperances" },
        いぜん: { 読み方: ['以前'], form: '名詞、副詞', 意味: "ago; since; before; previous" },
        おそれ: { 読み方: ['恐れ'], form: '名詞', 意味: "fear; horror; anxiety; concern" },
        もちさる: { 読み方: ['持ち去る'], form: '五段動詞', 意味: "to take away; to carry away" },
        もちぬし: { 読み方: ['持ち主'], form: '名詞', 意味: "owner" },
        うらがわ: { 読み方: ['裏側'], form: '名詞、の形容詞', 意味: "the reverse; the other side" },
        きにいる: { 読み方: ['気に入る'], form: '表現； 五段動詞', 意味: "to like; to take a liking to; to suit one's fancy" },
        こす: { 読み方: ['越す'], form: '五段動詞、尊敬語', 意味: "to go; to come" },
        じじつ: { 読み方: ['事実'], form: '副詞、名詞', 意味: "fact; truth; reality" },

        // Unit 1_2
        まど: { 読み方: ['窓'], form: '名詞', 意味: "window" },
        くみあわせる: { 読み方: ['組み合わせる'], form: '一段動詞、他動詞', 意味: "to join together; to combine" },
        にる: { 読み方: ['似る'], form: '一段動詞、自動詞', 意味: "to resemble; to be similar" },
        くぎる: { 読み方: ['区切る'], form: '五段動詞、他動詞', 意味: "to divide (an area)" },
        たとえば: { 読み方: ['例えば'], form: '副詞', 意味: "for example" },
        ばあい: { 読み方: ['場合'], form: '名詞', 意味: "case; situation" },
        おたがい: { 読み方: ['お互い'], form: '名詞、副詞', 意味: "each other; one another" },
        あたえる: { 読み方: ['与える'], form: '一段動詞、他動詞', 意味: "to give (esp. to someone of lower status)" },
        こうてき: { 読み方: ['公的'], form: 'ナ形容詞', 意味: "public" },
        してき: { 読み方: ['私的'], form: 'ナ形容詞', 意味: "private" },
        にんげん: { 読み方: ['人間'], form: '名詞', 意味: "human being" },
        ばめん: { 読み方: ['場面'], form: '名詞', 意味: "scene; setting; place (where something happens)" },
        ひつよう: { 読み方: ['必要'], form: 'ナ形容詞', 意味: "necessary" },

        // Unit 2_1
        なかま: { 読み方: ['仲間'], form: '名詞', 意味: "companion; friend; comrade" },
        ふうけい: { 読み方: ['風景'], form: '名詞', 意味: "scenery" },
        しゃこうがくしゃ: { 読み方: ['社交学者'], form: '名詞', 意味: "sociologist" },
        こうきょう: { 読み方: ['公共'], form: '名詞', 意味: "public (facilities, service, etc.)" },
        よこ: { 読み方: ['横'], form: '名詞', 意味: "horizontal; side-to-side (as opposed to front-to-back)" },
        うつる: { 読み方: ['映る'], form: '五段動詞、自動詞', 意味: "to be reflected; to be projected; to be displayed" },
        しんらいせい: { 読み方: ['信頼性'], form: '名詞', 意味: "credibility; reliability" },
        ほうそく: { 読み方: ['法則'], form: '名詞', 意味: "rule; law" },
        つうじる: { 読み方: ['通じる'], form: '一段動詞、自動詞', 意味: "to apply; to lead; to get across" },
        まんいん: { 読み方: ['満員'], form: '名詞', 意味: "full house; no vacancy" },
        かぐ: { 読み方: ['家具'], form: '名詞', 意味: "furniture" },
        しゃりょう: { 読み方: ['車両'], form: '名詞', 意味: "railroad car; wheeled vehicle" },
        かんかく: { 読み方: ['感覚'], form: '名詞、スル動詞', 意味: "sense; sensation; feeling; intuition" },
        へいき: { 読み方: ['平気'], form: 'ナ形容詞', 意味: "all right; fine; okay" },
        つくえ: { 読み方: ['机'], form: '名詞', 意味: "desk" },
        なぞ: { 読み方: ['謎'], form: '名詞', 意味: "mystery" },
        とく: { 読み方: ['解く'], form: '五段動詞、他動詞', 意味: "to solve; to work out; to answer" },
        かって: { 読み方: ['勝手'], form: '名詞、ナ形容詞', 意味: "one's own convenience; one's way; selfishness" },
        ぜんいん: { 読み方: ['全員'], form: '名詞、副詞', 意味: "all members; whole crew; everyone" },
        きょうゆう: { 読み方: ['共有'], form: '名詞、スル動詞', 意味: "join ownership; sharing (e.g. a viewpoint; files)" },
        ちょくせつ: { 読み方: ['直接'], form: 'ナ形容詞、名詞', 意味: "direct; immediate; firsthand" },
        かぎり: { 読み方: ['限り'], form: '動詞＋～限り', 意味: "as long as~" },

        // Unit 2_2
        こんご: { 読み方: ['今後'], form: '名詞、副詞', 意味: "from now on; hereafter" },
        いしき: { 読み方: ['意識'], form: '名詞、スル動詞', 意味: "consciousness; becoming aware (of); awareness" },
        しかたない: { 読み方: ['仕方ない'], form: 'イ形容詞', 意味: "there's no (other) way; cannot be helped" },
        いっぽう: { 読み方: ['一方'], form: '接続詞', 意味: "on the other hand" },
        いがい: { 読み方: ['意外'], form: 'ナ形容詞', 意味: "unexpected; surprising" },
        こうど: { 読み方: ['高度'], form: 'ナ形容詞', 意味: "high-degree; high-grade; advanced; sophisticated" },
        ようする: { 読み方: ['要する'], form: 'スル動詞、他動詞', 意味: "to need; to demand; to require" },
        つかれる: { 読み方: ['疲れる'], form: '一段動詞、自動詞', 意味: "to get tired; to tire; to get fatigued" },
        りせい: { 読み方: ['理性'], form: '名詞', 意味: "reasoning; (sense of) reason" },
        えきいん: { 読み方: ['駅員'], form: '名詞', 意味: "(train) station staff/employee" },
        かてい: { 読み方: ['家庭'], form: '名詞', 意味: "home; family; household" },
        きがえる: { 読み方: ['着替える'], form: '一段動詞', 意味: "to change one's clothes" },
        じっこう: { 読み方: ['実行'], form: '名詞、スル動詞', 意味: "execution (e.g. of a plan); carrying out" },
        しよう: { 読み方: ['使用'], form: '名詞、スル動詞', 意味: "use; application; utilization" },
        こごえ: { 読み方: ['小声'], form: '名詞、ノ形容詞', 意味: "low voice; whisper" },
        こしつ: { 読み方: ['個室'], form: '名詞', 意味: "private room; single room" },
        あんぜん: { 読み方: ['安全'], form: 'ナ形容詞', 意味: "safety;security" },

        // Unit 3_1
        ちきゅう: { 読み方: ['地球'], form: '名詞', 意味: "Earth; the globe" },
        おんだんか: { 読み方: ['温暖化'], form: '名詞、スル動詞', 意味: "warming" },
        りよう: { 読み方: ['利用'], form: '名詞、スル動詞', 意味: "use; utilization" },
        ふろ: { 読み方: ['風呂'], form: '名詞', 意味: "bath" },
        にゅうよく: { 読み方: ['入浴'], form: '名詞、スル動詞', 意味: "bathing; to take a bath; to enter a bath" },
        ほおん: { 読み方: ['保温'], form: '名詞、スル動詞', 意味: "retaining heat; heat insulation" },
        つめこむ: { 読み方: ['詰め込む'], form: '五段動詞、他動詞', 意味: "to cram; to stuff; to pack" },
        てきせつ: { 読み方: ['適切'], form: 'ナ形容詞', 意味: "appropriate; suitable" },
        せつやく: { 読み方: ['節約'], form: '名詞、スル動詞', 意味: "economising; saving" },
        かんきょう: { 読み方: ['環境'], form: '名詞', 意味: "environment" },
        ぼうし: { 読み方: ['防止'], form: '名詞、スル動詞', 意味: "prevention" },
        かつどう: { 読み方: ['活動'], form: '名詞、スル動詞', 意味: "activity" },
        ちょうせつ: { 読み方: ['調節'], form: '名詞、スル動詞', 意味: "regulation; adjustment; control" },
        せっち: { 読み方: ['設置'], form: '名詞、スル動詞', 意味: "installation" },
        でんきゅう: { 読み方: ['電球'], form: '名詞', 意味: "light bulb" },
        かでんせいひん: { 読み方: ['家電製品'], form: '名詞', 意味: "consumer electronics; home appliances" },

        // Unit 3_2
        しんや: { 読み方: ['深夜'], form: '名詞、副詞', 意味: "late at night" },
        わり: { 読み方: ['割'], form: '接尾詞', 意味: "rate; ratio; proportion; profit; 10%" },
        おんすい: { 読み方: ['温水'], form: '名詞', 意味: "warm　water" },
        あっか: { 読み方: ['悪化'], form: '名詞、スル動詞', 意味: "growing worse; (suffer) deterioration" },
        まねく: { 読み方: ['招く'], form: '五段動詞、他動詞', 意味: "to invite; to ask; to beckcon" },
        ふせぐ: { 読み方: ['防ぐ'], form: '五段動詞、他動詞', 意味: "to defend against; to protect against; to prevent" },
        うけいれる: { 読み方: ['受け入れる'], form: '一段動詞、他動詞', 意味: "to accept; to receive; to agree" },
        えいぎょう: { 読み方: ['営業'], form: '名詞、スル動詞', 意味: "business; trade; operations" },
        たいはん: { 読み方: ['大半'], form: '名詞', 意味: "majority; more than half; most (of)" },
        てがる: { 読み方: ['手軽'], form: 'ナ形容詞', 意味: "easy; simple; cheap" },
        じつげん: { 読み方: ['実現'], form: '名詞、スル動詞', 意味: "implementation (e.g. of a system); realization" },
        ちゅうもく: { 読み方: ['注目'], form: '名詞、スル動詞', 意味: "notice; attention" },
        うしなう: { 読み方: ['失う'], form: '五段動詞、他動詞', 意味: "to lose; to miss (a change, opportunity)" },
        たいさく: { 読み方: ['～対策'], form: '名詞', 意味: "counterplan; countermeasure; measures against~" },
        ちいき: { 読み方: ['地域'], form: '名詞', 意味: "area; region" },
        あさい: { 読み方: ['浅い'], form: 'イ形容詞', 意味: "shallow" },
        せだい: { 読み方: ['世代'], form: '名詞', 意味: "generatin; the world; the age" },
        きたい: { 読み方: ['期待'], form: '名詞、スル動詞', 意味: "expectation; anticipation; hope" },
        かつどうか: { 読み方: ['活動家'], form: '名詞', 意味: "activist" },
        さいりよう: { 読み方: ['再利用'], form: '名詞、スル動詞', 意味: "reuse; recycling" },
        へんか: { 読み方: ['変化'], form: '名詞、スル動詞', 意味: "change; variation; transform" },
        せいかつひ: { 読み方: ['生活費'], form: '名詞', 意味: "living expenses" },
        しみん: { 読み方: ['市民'], form: '名詞', 意味: "citizen" },

        
        // : { 読み方: [''], form: '', 意味: "" },
    },

    yomerebaii: {
        // Unit 1_1
        珍しい: { 読み方: ['めずらしい'], form: 'い形容詞', 意味: "unusual; rare; new" },
        洗濯: { 読み方: ['せんたく'], form: '名詞、する動詞', 意味: "washing; laundry" },
        電源コード: { 読み方: ['でんげんコード'], form: '名詞', 意味: "power cord" },
        延びる: { 読み方: ['のびる'], form: '一段動詞、自動詞', 意味: "to stretch; to extend; to lengthen; to grow; to be prolonged (meeting; lifespan)" },
        泥: { 読み方: ['どろ'], form: '名詞', 意味: "mud" },
        側面: { 読み方: ['そくめん'], form: '名詞', 意味: "side; flank" },
        明記: { 読み方: ['めいき'], form: '名詞、する動詞、他動詞', 意味: "to make clear; specification" },
        塩: { 読み方: ['しお'], form: '名詞', 意味: "salt" },
        製: { 読み方: ['〜せい'], form: '接尾詞', 意味: "-made; make" },
        振る: { 読み方: ['ふる'], form: '五段動詞、他動詞', 意味: "to wave; to shake" },
        奥: { 読み方: ['おく'], form: '名詞', 意味: "(further in) back" },
        事態: { 読み方: ['じたい'], form: '名詞', 意味: "state (of affairs/things); circumstances" },
        比較的: { 読み方: ['ひかくてき'], form: '副詞', 意味: "comparatively; relatively" },

        // Unit 1_2
        提案: { 読み方: ['ていあん'], form: '名詞、スル動詞', 意味: "to propose; suggestion" },
        縦軸: { 読み方: ['たてじく'], form: '名詞', 意味: "vertical axis" },
        横軸: { 読み方: ['よこじく'], form: '名詞', 意味: "horizontal axis" },
        印象: { 読み方: ['いんしょう'], form: '名詞、スル動詞', 意味: "impression" },
        発想: { 読み方: ['はっそう'], form: '名詞、スル動詞', 意味: "idea; conception" },
        状況: { 読み方: ['じょうきょう'], form: '名詞', 意味: "situation; circumstances" },
        分かち合う: { 読み方: ['わかちあう'], form: '五段動詞、他動詞', 意味: "to share" },
        留める: { 読み方: ['(心に）とめる'], form: '一段動詞、他動詞', 意味: "to bear in mind" },

        // Unit 2_1
        電柱: { 読み方: ['でんちゅう'], form: '名詞', 意味: "utility pole; telephone pole" },
        植木鉢: { 読み方: ['うえきばち'], form: '名詞', 意味: "potted plant" },
        化粧: { 読み方: ['けしょう'], form: '名詞、スル動詞', 意味: "make-up" },
        弁当: { 読み方: ['べんとう'], form: '名詞', 意味: "boxed-lunch" },
        迷惑: { 読み方: ['めいわく'], form: '名詞、ナ形容詞', 意味: "trouble; bother; annoyance; inconvenience" },
        被害: { 読み方: ['ひがい'], form: '名詞', 意味: "damage; injury; harm" },
        及ぶ: { 読み方: ['およぶ'], form: '五段動詞、自動詞', 意味: "to reach" },
        不愉快: { 読み方: ['ふゆかい'], form: 'ナ形容詞', 意味: "unpleasant" },

        // Unit 2_2
        標準: { 読み方: ['ひょうじゅん'], form: '名詞', 意味: "standard; norm" },
        暴力的: { 読み方: ['ぼうりょくてき'], form: 'ナ形容詞', 意味: "violent" },
        載る: { 読み方: ['のる'], form: '五段動詞、自動詞', 意味: "to be placed on; to appear (in print)" },
        酔っ払う: { 読み方: ['よっぱらう'], form: '五段動詞、自動詞', 意味: "to get drunk" },
        意志: { 読み方: ['いし'], form: '名詞', 意味: "will; intention; intent; determination" },
        弱まる: { 読み方: ['よわまる'], form: '五段動詞、自動詞', 意味: "to abate; to weaken; to be emaciated" },
        寛大: { 読み方: ['かんだい'], form: 'ナ形容詞、名詞', 意味: "tolerant; generous; lenient" },
        無視: { 読み方: ['むし'], form: '名詞、スル動詞', 意味: "ignoring; disregarding" },
        周囲: { 読み方: ['しゅうい'], form: '名詞', 意味: "surroundings" },
        踊る: { 読み方: ['おどる'], form: '五段動詞、自動詞', 意味: "to dance" },
        耐える: { 読み方: ['たえる'], form: '一段動詞、自動詞、他動詞', 意味: "to bear; to stand; to endure; to put up with" },
        続出: { 読み方: ['ぞくしゅつ'], form: '名詞、スル動詞', 意味: "appearing one after another" },
        携帯電話: { 読み方: ['けいたいでんわ'], form: '名詞', 意味: "cellular phone" },
        保つ: { 読み方: ['たもつ'], form: '五段動詞、他動詞', 意味: "to keep; to preserve; to maintain" },
        光景: { 読み方: ['こうけい'], form: '名詞', 意味: "scene; spectacle; sight; view" },

        // Unit 3_1
        排出量: { 読み方: ['はいしゅつりょう'], form: '名詞', 意味: "amount of emission" },
        二酸化炭素: { 読み方: ['にさんかたんそ'], form: '名詞', 意味: "carbon dioxide" },
        冷房: { 読み方: ['れいぼう'], form: '名詞、スル動詞', 意味: "air conditioning; air cooling" },
        暖房: { 読み方: ['だんぼう'], form: '名詞、スル動詞', 意味: "(indoor) heating" },
        洗濯: { 読み方: ['せんたく'], form: '名詞、スル動詞', 意味: "laundry" },
        冷蔵庫: { 読み方: ['れいぞうこ'], form: '名詞', 意味: "refrigerator" },
        削減: { 読み方: ['さくげん'], form: '名詞、スル動詞', 意味: "reduction" },
        間隔: { 読み方: ['かんかく'], form: '名詞', 意味: "space; interval" },
        炎: { 読み方: ['ほのお'], form: '名詞', 意味: "fire; flame" },
        設定温度: { 読み方: ['せっていおんど'], form: '名詞', 意味: "preset temperature" },
        推進: { 読み方: ['すいしん'], form: '名詞、スル動詞', 意味: "promotion; propulsion" },
        購入: { 読み方: ['こうにゅう'], form: '名詞、スル動詞', 意味: "purchase; buy" },
        洗剤: { 読み方: ['せんざい'], form: '名詞', 意味: "detergent" },
        燃費: { 読み方: ['ねんぴ'], form: '名詞', 意味: "fuel consumption; gas mileage" },
        鉄道: { 読み方: ['てつどう'], form: '名詞', 意味: "rail; railroad" },
        参考: { 読み方: ['さんこう'], form: '名詞', 意味: "reference" },

        // Unit 3_2
        我慢: { 読み方: ['がまん'], form: '名詞、スル動詞', 意味: "endurance; patience; perseverance; bearing (with something); self-control" },
        快適: { 読み方: ['かいてき'], form: 'ナ形容詞、名詞', 意味: "pleasant; agreeable; comfortable" },
        想定: { 読み方: ['そうてい'], form: '名詞、スル動詞', 意味: "hypothesis; assumption" },
        手放す: { 読み方: ['てばなす'], form: '五段動詞、他動詞', 意味: "to let go of; to release; to part with (e.g. a posession)" },
        値する: { 読み方: ['あたいする'], form: 'スル動詞（含まれている）、自動詞', 意味: "to be worth; to deserve" },
        普及: { 読み方: ['ふきゅう'], form: '名詞、スル動詞', 意味: "diffusion; spread; popularization; familiarization" },
        派: { 読み方: ['～は'], form: '名詞、接尾詞', 意味: "clique; group" },
        従う: { 読み方: ['したがう'], form: '五段動詞、自動詞', 意味: "to follow; to go alongside" },
        脱: { 読み方: ['だつ～'], form: '接頭辞', 意味: "de~ (indicating reversal, removal, etc.)" },
        程度: { 読み方: ['ていど'], form: '名詞', 意味: "degree; amount" },
        占める: { 読み方: ['しめる'], form: '一段動詞、他動詞', 意味: "to account for; to occupy" },
        輸送: { 読み方: ['ゆそう'], form: '名詞、スル動詞', 意味: "transport; transportation" },
        鐡道: { 読み方: ['てつどう'], form: '名詞', 意味: "railway; railroad" },
        次第: { 読み方: ['~しだい'], form: '名詞、接尾辞', 意味: "depending on~" },
        資源: { 読み方: ['しげん'], form: '名詞', 意味: "resources" },
        無駄: { 読み方: ['むだ'], form: '名詞、ナ形容詞', 意味: "futility; waste; uselessness; pointlessness" },
        無駄遣い: { 読み方: ['むだづかい'], form: '名詞、スル動詞', 意味: "waste (of money, time, etc.)" },
        政府: { 読み方: ['せいふ'], form: '名詞', 意味: "government" },
        面: { 読み方: ['めん'], form: '名詞', 意味: "face; aspect; side" },
        不可欠: { 読み方: ['ふかけつ'], form: 'ナ形容詞、名詞', 意味: "indespensable; essential" },
        燃料: { 読み方: ['ねんりょう'], form: '名詞', 意味: "fuel" },

        // : { 読み方: [''], form: '', 意味: "" },
    }
}

export default kanji;